export declare const StyledWrapper: any;
export declare const StyledLeft: any;
export declare const StyledRight: any;
export declare const StyledLogo: any;
export declare const StyledTitle: any;
export declare const StyledTM: any;
export declare const StyleTitle: any;
export declare const StyleText: any;
export declare const StyledContent: any;
