module.exports = {
	multipass: true,
	floatPrecision: 5,
	plugins: [
		"cleanupAttrs",
		"removeDoctype",
		"removeXMLProcInst",
		"removeComments",
		"removeMetadata",
		"removeTitle",
		"removeDesc",
		"removeUselessDefs",
		"removeEditorsNSData",
		"removeEmptyAttrs",
		"removeHiddenElems",
		"removeEmptyText",
		"removeEmptyContainers",
		"cleanupEnableBackground",
		"convertStyleToAttrs",
		"convertColors",
		"convertPathData",
		"convertTransform",
		"removeUnknownsAndDefaults",
		"removeNonInheritableGroupAttrs",
		"removeUselessStrokeAndFill",
		"removeUnusedNS",
		"cleanupIDs",
		"cleanupNumericValues",
		"moveElemsAttrsToGroup",
		"moveGroupAttrsToElems",
		"collapseGroups",
		"mergePaths",
		"convertShapeToPath",
		"sortAttrs",
		"removeDimensions",
		{
			name: "removeAttrs",
			params: { attrs: "(stroke|fill)" },
		},
	],
};
