// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M19.6039 12.1887a.8683.8683 0 0 1-.2674.6267l-6.1904 5.932c-.3461.3317-.8955.32-1.2272-.0261-.3316-.3461-.3199-.8955.0262-1.2272l4.6306-4.4375H6.87186c-.47937 0-.86797-.3886-.86797-.8679 0-.4794.3886-.868.86797-.868h9.70374l-4.6305-4.43731c-.3461-.33167-.3578-.88111-.0262-1.22722.3317-.34611.8811-.35782 1.2272-.02615l6.1904 5.93198a.86813.86813 0 0 1 .2674.6267z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
