// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M6.19006 12.0001a.79993.79993 0 0 1 .24649-.5776l6.26125-6.00009c.319-.3057.8254-.29491 1.1311.02409.3057.31901.2949.82542-.0241 1.13112L8.98114 11.2001H18.9901c.4418 0 .8.3581.8.8 0 .4418-.3582.8-.8.8H8.98117l4.82363 4.6223c.319.3057.3298.8121.0241 1.1311-.3057.319-.8121.3298-1.1311.0241l-6.26125-5.9999a.79997.79997 0 0 1-.24649-.5776z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
