// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M12.4196 18.9887a.80044.80044 0 0 1-.5777-.2465l-6.00001-6.2613c-.3057-.319-.29491-.8254.02409-1.1311.31901-.3057.82542-.2949 1.13112.0241l4.6225 4.8237V6.18867c0-.44183.3581-.8.8-.8.4418 0 .8.35817.8.8V16.1976l4.6223-4.8237c.3057-.319.8121-.3298 1.1311-.0241.319.3057.3298.8121.0241 1.1311l-5.9999 6.2613a.80039.80039 0 0 1-.5776.2465z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
