// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M12.6301 5.01129c.2181 0 .4267.08903.5776.24649l6.0001 6.26122c.3057.319.2949.8255-.0241 1.1311-.319.3057-.8254.295-1.1311-.024l-4.6225-4.82373V17.8113c0 .4418-.3581.8-.8.8-.4418 0-.8-.3582-.8-.8V7.8024L7.2078 12.626c-.3057.3191-.81211.3298-1.13112.0242-.319-.3057-.3298-.8122-.0241-1.1312l5.99992-6.26121a.79998.79998 0 0 1 .5776-.2465z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
