// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M16.3171 6.09287h-.2251c-.3322.09724-.5749.40423-.5749.76789v2.13333h3.0223c.1444 0 .2764-.05299.3777-.1406v-.16062c0-1.43594-1.164-2.6-2.6-2.6zm0-1.4c.6847 0 1.3292.17203 1.8927.47523 1.2419.55452 2.1073 1.80029 2.1073 3.24821 0 .03713-.0011.074-.0033.11056.0022.05506.0033.1104.0033.166v8.00003c0 2.2091-1.7908 4-4 4H8.31714c-2.20914 0-4-1.7909-4-4V8.69287c0-2.20914 1.79086-4 4-4h7.99996zm2.2223 5.50123c.1296 0 .256-.0139.3777-.0402v6.539c0 1.4359-1.164 2.6-2.6 2.6H8.31714c-1.43594 0-2.6-1.1641-2.6-2.6V8.69287c0-1.43594 1.16406-2.6 2.6-2.6h6.15276c-.0984.23644-.1528.49582-.1528.76789v2.33333c0 .55229.4478 1.00001 1 1.00001h3.2223zM7.61464 8.80784c-.33137 0-.6.26863-.6.6s.26863.59996.6.59996h3.99996c.3314 0 .6-.26859.6-.59996 0-.33137-.2686-.6-.6-.6H7.61464zm-.60002 2.93726c0-.3314.26863-.6.6-.6h7.99998c.3314 0 .6.2686.6.6 0 .3313-.2686.6-.6.6H7.61462c-.33137 0-.6-.2687-.6-.6zm.6 1.8661c-.33137 0-.6.2687-.6.6001 0 .3313.26863.6.6.6h7.99998c.3314 0 .6-.2687.6-.6 0-.3314-.2686-.6001-.6-.6001H7.61462z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
