// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M7.86577 4.69281c-.49706 0-.9.40295-.9.9v1.13361h-.30018c-.55229 0-1 .44772-1 1V19.6944c0 .5523.44771 1 1 1H19.2812c.5523 0 1-.4477 1-1v-8.9778c0-.5523-.4477-1.00002-1-1.00002h-3.6156V7.72642c0-.55228-.4477-1-1-1h-.2998V5.59281c0-.49706-.403-.9-.9-.9H7.86577zm.5 1.99543v-.59543h4.60003v.59543H8.36577zM7.06559 8.12642V19.2944h1v-2.5863c0-1.4359 1.16406-2.6 2.60001-2.6 1.4359 0 2.6 1.1641 2.6 2.6v2.5863h1V8.12642H7.06559zm8.61561 2.99018v8.1778h3.2v-8.1778h-3.2zm-5.0156 4.1915c-.77321 0-1.40001.6268-1.40001 1.4v2.3886h2.80001v-2.3886c0-.7732-.6268-1.4-1.4-1.4zM8.4328 8.74658c-.33137 0-.6.26863-.6.6s.26863.6.6.6h.79626c.33137 0 .6-.26863.6-.6s-.26863-.6-.6-.6H8.4328zm-.6 2.94702c0-.3314.26863-.6.6-.6h.79626c.33137 0 .6.2686.6.6s-.26863.6-.6.6H8.4328c-.33137 0-.6-.2686-.6-.6zm4.3529-2.94702c-.3313 0-.6.26863-.6.6s.2687.6.6.6h.7963c.3314 0 .6-.26863.6-.6s-.2686-.6-.6-.6h-.7963zm4.0288 3.65052c0-.3313.2686-.6.6-.6h.7963c.3313 0 .6.2687.6.6 0 .3314-.2687.6-.6.6h-.7963c-.3314 0-.6-.2686-.6-.6zm-4.0288-1.3035c-.3313 0-.6.2686-.6.6s.2687.6.6.6h.7963c.3314 0 .6-.2686.6-.6s-.2686-.6-.6-.6h-.7963zm4.0288 3.7487c0-.3314.2686-.6.6-.6h.7963c.3313 0 .6.2686.6.6s-.2687.6-.6.6h-.7963c-.3314 0-.6-.2686-.6-.6zm.6 1.8453c-.3314 0-.6.2686-.6.6 0 .3313.2686.6.6.6h.7963c.3313 0 .6-.2687.6-.6 0-.3314-.2687-.6-.6-.6h-.7963z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
