// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path d='M12.5016 20c4.4183 0 8-3.5817 8-8 0-4.41828-3.5817-8-8-8-4.41823 0-7.99995 3.58172-7.99995 8 0 4.4183 3.58172 8 7.99995 8zm-2.1718-7.8841 1.4816 1.2533 3.0419-4.17981c.26-.35724.7604-.43608 1.1176-.17609.3572.25999.4361.76034.1761 1.1176l-3.2952 4.5277c-.4102.5638-1.2129.6604-1.7452.2101l-1.81012-1.5312c-.33733-.2854-.37946-.7902-.09411-1.1275.28535-.3373.79013-.3794 1.12743-.0941z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
