// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M6.14241 12c0-3.61496 2.93049-6.54546 6.54549-6.54546 3.6149 0 6.5454 2.9305 6.5454 6.54546 0 3.6149-2.9305 6.5454-6.5454 6.5454-3.615 0-6.54549-2.9305-6.54549-6.5454zm6.54549-8c-4.41832 0-8.00003 3.58172-8.00003 8 0 4.4183 3.58171 8 8.00003 8 4.4182 0 7.9999-3.5817 7.9999-8 0-4.41828-3.5817-8-7.9999-8zm-2.1721 8.1159 1.4816 1.2533 3.0419-4.17983c.26-.35724.7604-.43608 1.1176-.17609.3573.25998.4361.76034.1761 1.11762l-3.2951 4.5277c-.4103.5637-1.213.6604-1.7453.2101l-1.8101-1.5313c-.33732-.2853-.37946-.7901-.09411-1.1274.28536-.3373.79011-.3795 1.12741-.0941z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
