// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M18.2317 7.84436c.4219-.42192.4219-1.10599 0-1.52792-.4219-.42192-1.106-.42192-1.5279 0l-4.1557 4.15566-4.15556-4.15547c-.42193-.42193-1.10601-.42193-1.52794 0-.42193.42192-.42193 1.10599 0 1.52792L11.0201 12l-4.1555 4.1555c-.42193.4219-.42193 1.1059 0 1.5279.42193.4219 1.10601.4219 1.52794 0l4.15556-4.1555 4.1557 4.1557c.4219.4219 1.106.4219 1.5279 0 .4219-.422.4219-1.106 0-1.528L14.076 12l4.1557-4.15564z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
