// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M16.7783 7.38696a.79969.79969 0 0 1 .2343.56569v7.07115c0 .4418-.3581.8-.8.8-.4418 0-.8-.3582-.8-.8V9.88402L8.55096 16.7457c-.31242.3124-.81895.3124-1.13137 0-.31242-.3124-.31242-.8189 0-1.1314l6.86171-6.86163-5.1397.00005c-.44183.00001-.8-.35816-.80001-.79999 0-.44183.35817-.8.8-.80001l7.07101-.00007c.2122 0 .4157.08428.5657.23431z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
