// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='m14.2587 5.64901 4.8341 4.83409c1.0153 1.0154 1.0153 2.6616 0 3.6769l-4.8341 4.8341c-1.0154 1.0154-2.6616 1.0154-3.677 0L5.74767 14.16c-1.01536-1.0153-1.01536-2.6615 0-3.6769l4.83413-4.83409c1.0153-1.01536 2.6615-1.01536 3.6769 0zm-4.6669-.98995c1.5621-1.5621 4.0948-1.5621 5.6569 0l4.834 4.83408c1.5621 1.56206 1.5621 4.09476 0 5.65686l-4.834 4.8341c-1.5621 1.5621-4.0948 1.5621-5.6569 0L4.75772 15.15c-1.5621-1.5621-1.56209-4.0948 0-5.65686L9.5918 4.65906zm5.9061 7.18624a.70008.70008 0 0 1-.2024.4961L13.441 14.216c-.2719.2749-.7151.2772-.9899.0053-.2749-.2718-.2773-.7151-.0054-.9899l.6551-.6621h-1.6457v2.0818c0 .3866-.3134.7-.7.7-.3866 0-.7-.3134-.7-.7v-2.7818c0-.3866.3134-.7.7-.7h2.36l-.664-.6567c-.2748-.2718-.2773-.71505-.0054-.98992.2718-.27488.715-.27733.9899-.00547l1.8545 1.83419a.69949.69949 0 0 1 .2078.4939z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
