// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M7.29014 6.81167H16.897c1.1475 0 2.0778.93025 2.0778 2.07778v.3014L12.425 13.93c-.1528.1105-.3589.1116-.5128.0026L5.21237 9.18953v-.30008c0-1.14753.93025-2.07778 2.07777-2.07778zM5.21237 10.5603v5.936c0 .097.00665.1925.01951.2859l3.69493-3.5923-3.71444-2.6296zm4.64279 3.2869-4.1303 4.0155c.38087.436.94092.7114 1.56528.7114H16.897c.5818 0 1.1077-.2391 1.4848-.6244l-4.0977-3.9839-1.2032.8706c-.5407.3912-1.2705.395-1.8152.0093l-1.41054-.9985zm10.23844 2.6491c0 .5732-.1509 1.1111-.4151 1.5763-.0262.0803-.0719.1559-.137.2199-.5752.8453-1.545 1.4004-2.6445 1.4004H7.29014c-1.76542 0-3.19657-1.4312-3.19657-3.1966V8.88945c0-1.76542 1.43115-3.19658 3.19657-3.19658H16.897c1.7654 0 3.1966 1.43116 3.1966 3.19658v7.60685zm-4.8897-3.1961 3.7269 3.6234c.0288-.1379.044-.2808.044-.4273v-5.9245l-3.7709 2.7284z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
