// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M11.2577 9.21713c.4686-.46862 1.2284-.46863 1.6971 0l4.7171 4.71717c.3124.3124.3124.8189 0 1.1314-.3124.3124-.8189.3124-1.1313 0l-4.4344-4.4344-4.43428 4.4344c-.31242.3124-.81895.3124-1.13137 0-.31242-.3125-.31242-.819 0-1.1314l4.71715-4.71717z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
