// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M13.6184 14.9716c-.4686.4686-1.2284.4686-1.697 0l-4.7172-4.7172c-.31242-.3124-.31242-.81893 0-1.13135.31242-.31242.81895-.31242 1.13137 0l4.43433 4.43435 4.4343-4.43435c.3124-.31242.819-.31242 1.1314 0s.3124.81895 0 1.13135l-4.7172 4.7172z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
