// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M5.79408 12.307c0-3.61496 2.9305-6.54545 6.54542-6.54545 3.615 0 6.5455 2.93049 6.5455 6.54545 0 3.6149-2.9305 6.5454-6.5455 6.5454-3.61492 0-6.54542-2.9305-6.54542-6.5454zm6.54542-7.99999c-4.41825 0-7.99996 3.58171-7.99996 7.99999 0 4.4183 3.58171 8 7.99996 8 4.4183 0 8-3.5817 8-8 0-4.41828-3.5817-7.99999-8-7.99999zm2.7936 5.20635c.2734.27337.2734.71654 0 .98994l-1.8037 1.8037 1.8037 1.8037c.2734.2734.2734.7166 0 .9899-.2733.2734-.7165.2734-.9899 0l-1.8037-1.8037-1.8036 1.8037c-.2734.2733-.71659.2733-.98996 0-.27336-.2734-.27336-.7166 0-.99l1.80366-1.8036-1.80366-1.8036c-.27336-.2734-.27336-.71659.00001-.98996.27336-.27336.71655-.27336.98995 0l1.8036 1.80356 1.8037-1.80364c.2734-.27336.7166-.27336.9899 0z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
