// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M18.7642 9.99715c-.8202-3.0981-3.9598-4.92405-7.0034-4.0986-.995.26984-1.85708.78864-2.5401 1.47321-.37774.37859-.68976.81509-.94872 1.29802l1.06584-.40272c.36164-.13664.76558.04576.90228.4074.1366.36165-.0458.76559-.40745.90224l-2.56791.9703c-.33057.1249-.7024-.0162-.86693-.329L5.19922 7.9395c-.17998-.34215-.04852-.76542.29362-.9454.34215-.17999.76542-.04853.94541.29362l.49038.93223c.33234-.66606.7558-1.29059 1.301-1.83702.85042-.85235 1.92597-1.49962 3.16467-1.83557 3.8065-1.03234 7.708 1.25626 8.7233 5.0915 1.0145 3.83214-1.2302 7.78214-5.0334 8.81364-2.5792.6995-5.20451-.1271-6.94235-1.9249-.26869-.278-.26117-.7211.01679-.9898.27796-.2687.72111-.2612.9898.0167 1.40016 1.4485 3.50556 2.1065 5.56936 1.5468 3.0469-.8264 4.8674-4.003 4.0464-7.10415zm-6.103-1.07834c.3866-.00001.7.31339.7.69999l.0001 2.3 2.2999-.0001c.3866 0 .7.3134.7.7.0001.3866-.3133.7-.6999.7l-3 .0001a.69989.69989 0 0 1-.7-.7l-.0001-2.99999c0-.3866.3134-.7.7-.7z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
