// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M16.4922 6.09287H8.49219c-1.43594 0-2.6 1.16406-2.6 2.6v8.00003c0 1.4359 1.16406 2.6 2.6 2.6h8.00001c1.4359 0 2.6-1.1641 2.6-2.6V8.69287c0-1.43594-1.1641-2.6-2.6-2.6zm-8.00001-1.4c-2.20914 0-4 1.79086-4 4v8.00003c0 2.2091 1.79086 4 4 4h8.00001c2.2091 0 4-1.7909 4-4V8.69287c0-2.20914-1.7909-4-4-4H8.49219zm5.45901 7.04823a.69952.69952 0 0 1 .5149.1561l2.9711 2.4468c.2984.2458.3411.6869.0953.9854-.2457.2984-.6869.3411-.9853.0953l-2.4269-1.9986-2.1723 2.676a.70027.70027 0 0 1-.482.2562.70036.70036 0 0 1-.5194-.1679l-1.14131-.987-1.25513 1.6569c-.23344.3081-.6725.3687-.98066.1352-.30816-.2334-.36873-.6725-.13529-.9806l1.70611-2.2522a.69998.69998 0 0 1 .4848-.2734.70005.70005 0 0 1 .53108.1666l1.16 1.0032 2.1614-2.6627a.69998.69998 0 0 1 .4736-.2553zM8.34104 9.29042c0-.27614.22385-.5.5-.5.27614 0 .5.22386.5.5s-.22386.5-.5.5c-.27615 0-.5-.22386-.5-.5zm.5-1.5c-.82843 0-1.5.67157-1.5 1.5 0 .82838.67157 1.49998 1.5 1.49998.82842 0 1.49996-.6716 1.49996-1.49998 0-.82843-.67154-1.5-1.49996-1.5z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
