// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M5.70058 12c0-3.61496 2.93049-6.54546 6.54542-6.54546 3.615 0 6.5455 2.9305 6.5455 6.54546 0 3.6149-2.9305 6.5454-6.5455 6.5454-3.61493 0-6.54542-2.9305-6.54542-6.5454zM12.246 4c-4.41825 0-7.99997 3.58172-7.99997 8 0 4.4183 3.58172 8 7.99997 8 4.4183 0 8-3.5817 8-8 0-4.41828-3.5817-8-8-8zm.9188 5.37038c0 .50754-.4115.91902-.919.91902-.5075 0-.919-.41148-.919-.91902 0-.50754.4115-.91899.919-.91899.5075 0 .919.41145.919.91899zm-.919 1.60232c.3866 0 .7.3134.7.7v3.6759c0 .3866-.3134.7-.7.7-.3866 0-.7-.3134-.7-.7v-3.6759c0-.3866.3134-.7.7-.7z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
