// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M7.73676 11.5351c0-2.99927 2.34324-5.38774 5.18184-5.38774 2.8385 0 5.1818 2.38847 5.1818 5.38774 0 1.465-.8581 3.4209-2.0401 5.0555-.5815.8041-1.213 1.4901-1.8032 1.9669-.6188.4999-1.0821.6808-1.3431.6808-.0749 0-.2246-.029-.4577-.1462-.2262-.1138-.4909-.2905-.7829-.5306-.5839-.4802-1.2242-1.1704-1.81999-1.9769-1.21384-1.6432-2.11665-3.595-2.11665-5.0495zm5.18184-6.84229c-3.68846 0-6.63639 3.08705-6.63639 6.84229 0 1.9226 1.12503 4.1861 2.40124 5.9138.64928.8789 1.36955 1.6632 2.06605 2.236.3482.2864.7037.5308 1.0532.7066.3426.1723.724.3013 1.1113.3013.7774 0 1.5725-.4507 2.2572-1.0039.7134-.5763 1.4304-1.3647 2.0678-2.246 1.2556-1.7364 2.3159-3.9956 2.3159-5.9078 0-3.75524-2.9479-6.84229-6.6363-6.84229zm-1.1191 6.65599c0-.6181.5011-1.1193 1.1193-1.1193s1.1193.5012 1.1193 1.1193c0 .6182-.5011 1.1193-1.1193 1.1193s-1.1193-.5011-1.1193-1.1193zm1.1193-2.51704c-1.3901 0-2.5171 1.12693-2.5171 2.51704 0 1.3902 1.127 2.5171 2.5171 2.5171 1.3901 0 2.5171-1.1269 2.5171-2.5171 0-1.39011-1.127-2.51704-2.5171-2.51704z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
