// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M18.7342 7.20006c0 .66274-.5373 1.2-1.2 1.2H7.93419c-.66274 0-1.2-.53726-1.2-1.2s.53726-1.2 1.2-1.2h9.60001c.6627 0 1.2.53726 1.2 1.2zm0 4.80004c0 .6627-.5373 1.2-1.2 1.2H7.93419c-.66274 0-1.2-.5373-1.2-1.2 0-.6628.53726-1.2 1.2-1.2h9.60001c.6627 0 1.2.5372 1.2 1.2zm-1.2 6c.6627 0 1.2-.5373 1.2-1.2 0-.6628-.5373-1.2-1.2-1.2H7.93419c-.66274 0-1.2.5372-1.2 1.2 0 .6627.53726 1.2 1.2 1.2h9.60001z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
