// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M16.2944 6.09275H8.29443c-1.43594 0-2.6 1.16406-2.6 2.6v7.99995c0 1.436 1.16406 2.6 2.6 2.6h7.99997c1.436 0 2.6-1.164 2.6-2.6V8.69275c0-1.43594-1.164-2.6-2.6-2.6zm-7.99997-1.4c-2.20914 0-4 1.79086-4 4v7.99995c0 2.2092 1.79086 4 4 4h7.99997c2.2092 0 4-1.7908 4-4V8.69275c0-2.20914-1.7908-4-4-4H8.29443zM10.3641 17.1554c-.1853 0-.3355-.1502-.3355-.3355 0-.1853.1502-.3355.3355-.3355.1853 0 .3355.1502.3355.3355 0 .1853-.1502.3355-.3355.3355zm-1.13756.3645c.23516.3813.65667.6355 1.13756.6355.4809 0 .9024-.2542 1.1375-.6355h4.1351c.3866 0 .7-.3134.7-.7 0-.3866-.3134-.7-.7-.7h-4.135c-.2351-.3813-.6567-.6355-1.1376-.6355-.48093 0-.90247.2542-1.13762.6355h-.2739c-.3866 0-.7.3134-.7.7 0 .3866.3134.7.7.7h.27396zm5.43446-5.3538c.6667-.3849.6667-1.3472 0-1.7321l-3.3-1.90523c-.6666-.3849-1.49996.09622-1.49996.86602v3.81051c0 .7698.83336 1.2509 1.49996.866l3.3-1.9052zm-3.6-2.4249 2.7 1.5588-2.7 1.5589V9.7412z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
