// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M15.7302 11.3486c.4575.4666.4575 1.2136 0 1.6802l-5.7254 5.8395c-.30936.3155-.81586.3205-1.13135.0112-.31548-.3093-.32048-.8158-.01116-1.1313l5.45091-5.5595-5.45091-5.55946c-.30932-.31548-.30432-.82199.01116-1.13131.31549-.30933.822-.30433 1.13135.01116l5.7254 5.83951z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
