// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M8.80051 13.0288c-.45752-.4666-.45752-1.2136 0-1.6802l5.72539-5.83951c.3094-.31549.8159-.32048 1.1314-.01116.3154.30932.3204.81583.0111 1.13131l-5.4508 5.55946 5.4508 5.5595c.3093.3155.3043.822-.0111 1.1313-.3155.3093-.822.3043-1.1314-.0112l-5.72539-5.8395z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
