// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M18.9664 6.17135 14.9063 18.5321l-1.778-4.8611c-.2876-.7864-.9103-1.4038-1.699-1.6848l-4.70257-1.675L18.9664 6.17135zM16.0443 20.3289l4.7748-14.53657c.3016-.9182-.5745-1.78664-1.49-1.47698L4.92067 9.18879c-1.05376.35641-1.06566 1.84251-.01775 2.21581l5.97548 2.1284c.3286.117.5881.3743.7079.702l2.2423 6.1308c.3822 1.0449 1.8685 1.0201 2.2157-.0369z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
