// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M11.7566 7.2c0-.66274-.5372-1.2-1.2-1.2-.6627 0-1.19996.53726-1.19996 1.2v9.6c0 .6627.53726 1.2 1.19996 1.2.6628 0 1.2-.5373 1.2-1.2V7.2zm4.7212 0c0-.66274-.5372-1.2-1.2-1.2-.6627 0-1.2.53726-1.2 1.2v9.6c0 .6627.5373 1.2 1.2 1.2.6628 0 1.2-.5373 1.2-1.2V7.2z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
