// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M15.0482 13.2379c.7121-.4272.7121-1.4592 0-1.8865l-3.8225-2.2935c-.7332-.4399-1.66594.08822-1.66594.9432v4.5871c0 .855.93274 1.3831 1.66594.9432l3.8225-2.2935zm-4.0884-2.7069 2.9394 1.7637-2.9394 1.7636V10.531z'
    clip-rule='evenodd' />
    <path fill-rule='evenodd' d='M12.1182 4.30701c-4.4183 0-8.00002 3.58171-8.00002 7.99999 0 4.4183 3.58172 8 8.00002 8 4.4182 0 8-3.5817 8-8 0-4.41828-3.5818-7.99999-8-7.99999zM5.57272 12.307c0-3.61496 2.9305-6.54545 6.54548-6.54545 3.6149 0 6.5454 2.93049 6.5454 6.54545 0 3.6149-2.9305 6.5454-6.5454 6.5454-3.61498 0-6.54548-2.9305-6.54548-6.5454z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
