// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M17.7991 11.0988c.6256.4379.6256 1.3644 0 1.8023l-8.90244 6.2318c-.72906.5103-1.73081-.0113-1.73081-.9012V5.76823c0-.88992 1.00175-1.41149 1.73081-.90115l8.90244 6.23172zM8.56585 6.34443V17.6555L16.6452 12 8.56585 6.34443z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
