// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path d='M12.8966 20.307c4.4183 0 8-3.5817 8-8 0-4.41827-3.5817-7.99999-8-7.99999-4.41827 0-7.99999 3.58172-7.99999 7.99999 0 4.4183 3.58172 8 7.99999 8zm-1.2908-4.9406c-.2651.1856-.6294-.004-.6294-.3277V9.57527c0-.32361.3643-.51327.6294-.32769l3.9024 2.73172c.2275.1593.2275.4962 0 .6554l-3.9024 2.7317z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
