// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M9.37342 6.75323h4.63678c2.0434 0 3.7 1.65655 3.7 3.69997v4.8315c.5793-.2255.9899-.7888.9899-1.448V8.39183c0-1.27025-1.0297-2.3-2.3-2.3h-5.7122c-.5385 0-1.01622.26005-1.31448.6614zM17.457 16.7739c-.2599.6643-.7062 1.2347-1.2737 1.6472v1.5728c0 .2848-.1725.5412-.4363.6484-.2638.1073-.5663.044-.7651-.1599l-1.3211-1.356H7.79558c-2.04345 0-3.7-1.6566-3.7-3.7v-4.9732c0-2.04342 1.65655-3.69997 3.7-3.69997h.01567c.40623-1.19869 1.54068-2.0614 2.87665-2.0614h5.7122c2.0435 0 3.7 1.65655 3.7 3.7v5.44487c0 1.5264-1.1578 2.7822-2.6431 2.9372zM5.49558 10.4532c0-1.27022 1.02975-2.29997 2.3-2.29997h6.21462c1.2702 0 2.3 1.02975 2.3 2.29997v4.9732c0 .8588-.4705 1.6088-1.1711 2.0044a.70003.70003 0 0 0-.3558.6096v.2319l-.3259-.3344a.69948.69948 0 0 0-.5013-.2115H7.79558c-1.27025 0-2.3-1.0298-2.3-2.3v-4.9732zm1.63151 4.3627c0-.3866.3134-.7.7-.7h6.00001c.3866 0 .7.3134.7.7 0 .3866-.3134.7-.7.7H7.82709c-.3866 0-.7-.3134-.7-.7zm.7-3.8433c-.3866 0-.7.3134-.7.7 0 .3866.3134.7.7.7h6.00001c.3866 0 .7-.3134.7-.7 0-.3866-.3134-.7-.7-.7H7.82709z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
