// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 24'>
    <path fill-rule='evenodd' d='M6.52973 9.99721c.82017-3.0981 3.95977-4.92405 7.00337-4.0986.995.26984 1.8571.78864 2.5401 1.47321.3778.37859.6898.8151.9488 1.29802l-1.0659-.40272c-.3616-.13664-.7656.04576-.9022.4074-.1367.36165.0457.76559.4074.90224l2.5679.97024c.3413.129.7245-.0259.8803-.3558l1.0379-2.19718c.1651-.34956.0156-.76679-.3339-.93191-.3496-.16513-.7668-.01561-.932.33395l-.3539.74932c-.3265-.63809-.7385-1.23642-1.2633-1.76239-.8504-.85235-1.9259-1.49962-3.1647-1.83557-3.8065-1.03234-7.70793 1.25626-8.72324 5.09151-1.0145 3.83217 1.23019 7.78217 5.03334 8.81357 2.5792.6995 5.2045-.1271 6.9424-1.9249.2687-.2779.2612-.7211-.0168-.9898-.278-.2687-.7211-.2612-.9898.0168-1.4002 1.4485-3.5056 2.1064-5.5693 1.5467-3.04698-.8263-4.86745-4.0029-4.04647-7.10409z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
