// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path d='M14.045 4.79523c-.3866 0-.7.3134-.7.7V10.653c0 1.7296 1.2315 3.1715 2.8655 3.4967l-.0001.01v5.0309h-1.0192c-.3866 0-.7.3134-.7.7 0 .3866.3134.7.7.7h3.4385c.3866 0 .7-.3134.7-.7 0-.3866-.3134-.7-.7-.7h-1.0193v-5.0409c1.6339-.3252 2.8655-1.7671 2.8655-3.4967V5.49523c0-.3866-.3134-.7-.7-.7H14.045zm.7 4.09754V6.19523h4.3309V7.7423a.6019.6019 0 0 0-.1065.01856L14.745 8.89277zm0 1.23233a.60172.60172 0 0 0 .1065-.0185l4.2244-1.13195V10.653c0 1.1959-.9695 2.1654-2.1655 2.1654-1.1959 0-2.1654-.9695-2.1654-2.1654v-.5279zM6.4993 5.49524c0-.3866-.3134-.7-.7-.7-.3866 0-.7.3134-.7.7v4.87706c0 1.4911 1.20884 2.7 2.7 2.7h.36598v6.8183c0 .3866.3134.7.7.7.38659 0 .7-.3134.7-.7v-6.8183h.23402c1.4912 0 2.7-1.2089 2.7-2.7V5.49524c0-.3866-.3134-.7-.7-.7-.3866 0-.7.3134-.7.7v4.87706c0 .7179-.582 1.3-1.3 1.3h-.23402V5.49523c0-.3866-.31341-.7-.7-.7-.3866 0-.7.3134-.7.7v6.17707H7.7993c-.71797 0-1.3-.5821-1.3-1.3V5.49524z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
