// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M12.0202 6.09495c-3.28627 0-5.95895 2.68476-5.95895 6.00725 0 3.3225 2.67268 6.0073 5.95895 6.0073 3.2863 0 5.959-2.6848 5.959-6.0073 0-3.32249-2.6727-6.00725-5.959-6.00725zM4.66125 12.1022c0-4.08614 3.28997-7.40725 7.35895-7.40725 4.069 0 7.359 3.32111 7.359 7.40725 0 1.7718-.6186 3.3997-1.651 4.6755l2.7283 2.7171c.2739.2728.2748.716.002.9899-.2728.2739-.716.2748-.9899.002l-2.7198-2.7085c-1.2782 1.0802-2.927 1.7313-4.7286 1.7313-4.06898 0-7.35895-3.3212-7.35895-7.4073zm9.73505-2.0744c-.7123-.71747-1.5893-1.16412-2.508-1.34188-.3782-.0732-.626-.44142-.5533-.82245.0727-.38102.4382-.63057.8165-.55737 1.184.2291 2.3154.80581 3.2311 1.72818.7025.70753 1.2035 1.54342 1.5012 2.43352.1231.3677-.0731.7662-.4382.8901-.365.1239-.7606-.0737-.8836-.4414-.2307-.6895-.6187-1.3377-1.1657-1.8887z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
