// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M11.0611 16.5504V7.35044h2.2v9.19996h-2.2zM9.66115 6.95044c0-.55229.44775-1 .99995-1h3c.5523 0 1 .44771 1 1v9.99996c0 .5523-.4477 1-1 1h-3c-.5522 0-.99995-.4477-.99995-1V6.95044zM5.00956 16.5505v-5.2h2.2v5.2h-2.2zm-1.4-5.6c0-.5523.44772-1.00004 1-1.00004h3c.55229 0 1 .44774 1 1.00004v6c0 .5522-.44771 1-1 1h-3c-.55228 0-1-.4478-1-1v-6zm13.50324.4v5.2h2.2v-5.2h-2.2zm-.4-1.40004c-.5523 0-1 .44774-1 1.00004v6c0 .5522.4477 1 1 1h3c.5523 0 1-.4478 1-1v-6c0-.5523-.4477-1.00004-1-1.00004h-3zM4.16107 19.2926c-.38659 0-.7.3134-.7.7 0 .3866.31341.7.7.7H20.1611c.3866 0 .7-.3134.7-.7 0-.3866-.3134-.7-.7-.7H4.16107z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
