// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M15.3054 6.50559c0-.41255-.4336-.68128-.8031-.49768a.55594.55594 0 0 0-.2935.3699l-1.0853 4.59389c-.0668.2827-.3192.4825-.6097.4825h-1.5259v7.9839h6.5191c.1707 0 .3198-.1158.3619-.2813l1.7627-6.9215c.1008-.3961-.1985-.7811-.6072-.7811h-3.0925c-.346 0-.6265-.2805-.6265-.6265V6.50559zM6.15693 11.4542h3.57795v7.9839H6.15693v-7.9839zm7.78777-6.56836c1.2024-.59756 2.6137.27707 2.6137 1.61975v3.69561h2.466c1.2262 0 2.124 1.1551 1.8214 2.3433l-1.7626 6.9215c-.1836.7207-.8325 1.2251-1.5762 1.2251H5.53043c-.34601 0-.6265-.2805-.6265-.6265v-9.2369c0-.346.28049-.6265.6265-.6265H12.018l.9714-4.11148a1.80851 1.80851 0 0 1 .9553-1.20388zM7.89146 12.0773c-.55228 0-1 .4477-1 1 0 .5522.44772 1 1 1 .55229 0 1-.4478 1-1 0-.5523-.44771-1-1-1z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
