// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from '../icon-template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 25 25'>
    <path fill-rule='evenodd' d='M9.69838 18.8799c0 .4125.43362.6813.80312.4977a.55608.55608 0 0 0 .2935-.3699l1.0853-4.5939c.0668-.2827.3192-.4825.6098-.4825h1.5258V5.9474H7.49685c-.17077 0-.3198.11583-.36194.28132L5.37227 13.1502c-.10086.3961.19841.7811.60712.7811h3.09249c.34601 0 .6265.2805.6265.6265v4.3221zm9.14852-4.9486h-3.578V5.9474h3.578v7.9839zm-7.7878 6.5684c-1.20236.5975-2.61372-.2771-2.61372-1.6198v-3.6956H5.97939c-1.22615 0-2.12396-1.1551-1.82137-2.3433l1.76264-6.9215c.18353-.72069.8325-1.2251 1.57619-1.2251H19.4734c.346 0 .6265.28049.6265.6265v9.2369c0 .346-.2805.6265-.6265.6265h-6.4876l-.9714 4.1115a1.80883 1.80883 0 0 1-.9553 1.2039zm6.0533-7.1915c.5522 0 1-.4477 1-1 0-.5522-.4478-1-1-1-.5523 0-1 .4478-1 1 0 .5523.4477 1 1 1z'
    clip-rule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
