export declare const StyledWrapper: any;
export declare const StyledSelectWrapper: any;
export declare const StyledSelect: any;
export declare const StyledSelectArrow: any;
export declare const StyledSelectText: any;
export declare const StyledOptions: any;
export declare const StyledOption: any;
export declare const StyledOptionCheck: any;
export declare const StyledOptionText: any;
