// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' xmlnsXlink='http://www.w3.org/1999/xlink'
viewBox='0 0 32 32'>
    <defs>
        <path id='a' d='M24.75866 17H5c-.55229 0-1-.44772-1-1s.44771-1 1-1h19.75866l-6.78743-6.26519c-.40583-.3746-.43114-1.00726-.05654-1.41308.3746-.40583 1.00726-.43114 1.41308-.05654l8.13601 7.51c.71496.65997.71496 1.78965 0 2.44962l-8.136 7.51c-.40583.3746-1.03849.34929-1.41309-.05654-.3746-.40582-.34929-1.03848.05654-1.41308L24.75866 17z'
        />
    </defs>
    <use fillRule='evenodd' transform='rotate(-90 16 16)' xlinkHref='#a' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
