// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M23.87 27.855c.178.133.211.14.14.179-.046.025-.01-.058-.01-.329V5.245C24 4.55 23.481 4 22.882 4H9.118C8.519 4 8 4.55 8 5.246v22.459c0 .183.017.28.013.317-.047-.051.008-.085.118-.167l5.54-4.147c1.307-.98 3.352-.98 4.659 0l5.54 4.147zm-6.74-2.546c-.595-.448-1.664-.448-2.26 0l-5.54 4.146C7.702 30.676 6 29.741 6 27.705V5.245C6 3.472 7.388 2 9.118 2h13.764C24.612 2 26 3.471 26 5.246v22.459c0 2.036-1.7 2.971-3.33 1.75l-5.54-4.146z' />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
