// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M4.64018 21.76822c-.42427.35357-1.05484.29624-1.4084-.12804-.35357-.42427-.29624-1.05484.12804-1.4084l12-10c.37085-.30904.90953-.30904 1.28037 0l11.9997 10c.42428.35358.4816.98414.12802 1.40841-.35357.42428-.98413.4816-1.4084.12802l-11.35952-9.4665-11.3598 9.46651z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
