// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M10.23178 4.64018c-.35357-.42427-.29624-1.05484.12804-1.4084.42427-.35357 1.05484-.29624 1.4084.12804l10 12c.30904.37085.30904.90953 0 1.28037l-10 11.9997c-.35358.42428-.98414.4816-1.40841.12802-.42428-.35357-.4816-.98413-.12802-1.4084l9.4665-11.35952-9.46651-11.3598z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
