// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M28.9999 15.9997c0 7.168-5.832 13-13 13s-13-5.832-13-13c0-7.169 5.832-13 13-13s13 5.831 13 13zm-18.74-1.327l5 5.5c.379.417 1.101.417 1.48 0l5-5.5c.371-.409.341-1.042-.067-1.413-.408-.372-1.042-.342-1.413.067l-4.26 4.686-4.26-4.686c-.197-.217-.469-.327-.74-.327-.24 0-.482.086-.673.26-.408.371-.438 1.004-.067 1.413z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
