// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M18.7399 10.3267c.174.191.26.433.26.673 0 .271-.11.543-.327.74l-4.686 4.26 4.686 4.26c.409.371.439 1.005.067 1.413-.371.408-1.004.438-1.413.067l-5.5-5c-.417-.379-.417-1.101 0-1.48l5.5-5c.409-.371 1.042-.341 1.413.067zm-13.74 5.673c0 6.065 4.935 11 11 11 6.066 0 11-4.935 11-11 0-6.066-4.934-11-11-11-6.065 0-11 4.934-11 11zm24 0c0 7.168-5.831 13-13 13-7.168 0-13-5.832-13-13s5.832-13 13-13c7.169 0 13 5.832 13 13z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
