// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M2.9999 15.9997c0-7.168 5.831-13 13-13 7.168 0 13 5.832 13 13s-5.832 13-13 13c-7.169 0-13-5.832-13-13zm10.26 5.673c.371.408 1.004.438 1.413.067l5.5-5c.417-.379.417-1.101 0-1.48l-5.5-5c-.409-.371-1.042-.341-1.413.067-.372.408-.342 1.042.067 1.413l4.686 4.26-4.686 4.26c-.217.197-.327.469-.327.74 0 .24.086.482.26.673z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
