// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M15.9999 28.9997c-7.168 0-13-5.832-13-13s5.832-13 13-13c7.169 0 13 5.832 13 13s-5.831 13-13 13zm1.327-18.74l-5.5 5c-.417.379-.417 1.101 0 1.48l5.5 5c.409.371 1.042.341 1.413-.067.372-.408.342-1.042-.067-1.413l-4.686-4.26 4.686-4.26c.217-.197.327-.469.327-.74 0-.24-.086-.482-.26-.673-.371-.408-1.004-.438-1.413-.067z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
