// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M20.707 19.293a.999.999 0 1 1-1.414 1.414L16 17.414l-3.293 3.293a.997.997 0 0 1-1.414 0 .999.999 0 0 1 0-1.414L14.586 16l-3.293-3.293a.999.999 0 1 1 1.414-1.414L16 14.586l3.293-3.293a.999.999 0 1 1 1.414 1.414L17.414 16l3.293 3.293zM16 3C8.832 3 3 8.832 3 16s5.832 13 13 13 13-5.832 13-13S23.168 3 16 3z' />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
