// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M15.25 21.65a1 1 0 0 0 1.5 0l5.89-4.88a1 1 0 1 0-1.28-1.54L17 18.84V4a1 1 0 0 0-2 0v14.84l-4.36-3.61a1 1 0 0 0-1.28 1.54z'
    />
    <path d='M28 20a1 1 0 0 0-1 1v5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1v-5a1 1 0 0 0-2 0v5a3 3 0 0 0 3 3h20a3 3 0 0 0 3-3v-5a1 1 0 0 0-1-1z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
