// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M16 3a13 13 0 1 0 13 13A13 13 0 0 0 16 3zm0 24a11 11 0 1 1 11-11 11 11 0 0 1-11 11z'
    />
    <path d='M22.43 17.1a1 1 0 0 0-1.33.47A5.69 5.69 0 0 1 16 21a5.71 5.71 0 0 1-5.1-3.43 1 1 0 1 0-1.8.86A7.7 7.7 0 0 0 16 23a7.66 7.66 0 0 0 6.9-4.57 1 1 0 0 0-.47-1.33z'
    />
    <circle cx='12' cy='12' r='2' />
    <circle cx='20' cy='12' r='2' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
