// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M26.636 3H5.364A2.363 2.363 0 0 0 3 5.364v21.272A2.363 2.363 0 0 0 5.364 29h11.818V18.364h-3.546v-3.546h3.546v-1.904c0-3.604 1.756-5.187 4.752-5.187 1.435 0 2.193.107 2.553.155v3.39h-2.044c-1.271 0-1.716.672-1.716 2.031v1.515h3.728l-.506 3.546h-3.222V29h5.91A2.363 2.363 0 0 0 29 26.636V5.364A2.364 2.364 0 0 0 26.636 3z'
    />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
