// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path 
        d='M18.12 26.62a6.1 6.1 0 0 1-4.24 0 1 1 0 0 0-.67 1.89 8.19 8.19 0 0 0 5.58 0 1 1 0 0 0-.67-1.89zM25 13.27a13.41 13.41 0 0 0-.45-2.81l-.06-.23c0-.15-.09-.28-.14-.42a.56.56 0 0 0 0-.12A7.69 7.69 0 0 0 24 9c-1.49-3.53-4.48-6-8-6S9.49 5.44 8 9a7.69 7.69 0 0 0-.28.72.56.56 0 0 0 0 .12c0 .14-.1.27-.14.42l-.06.23A13.41 13.41 0 0 0 7 13.27V14c0 6 4 11 9 11s9-5 9-11v-.73zM16 5a5.78 5.78 0 0 1 3.27 1A7.53 7.53 0 0 0 16 7.26a7.53 7.53 0 0 0-3.27-1.21A5.78 5.78 0 0 1 16 5zm-7 9v-.53V13a12 12 0 0 1 .36-2 3.79 3.79 0 0 1 .14-.48c.08-.24.17-.47.26-.69 0-.06 0-.12.08-.17A2.33 2.33 0 0 1 12 8a5.14 5.14 0 0 1 2.35.61A12.12 12.12 0 0 0 11 17a13.32 13.32 0 0 0 .53 3.92A10.14 10.14 0 0 1 9 14zm7 9c-1.56 0-3-1.88-3-6a10.07 10.07 0 0 1 3-7.21A10.07 10.07 0 0 1 19 17c0 4.12-1.44 6-3 6zm4.47-2.08A13.32 13.32 0 0 0 21 17a12.12 12.12 0 0 0-3.35-8.39A5.14 5.14 0 0 1 20 8a2.33 2.33 0 0 1 2.08 1.56s0 .11.08.17c.09.22.18.45.26.69a3.79 3.79 0 0 1 .14.48 12 12 0 0 1 .36 2v1a10.14 10.14 0 0 1-2.45 7.02z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
