// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M27 4h-6V3a1 1 0 0 0-2 0v1h-6V3a1 1 0 0 0-2 0v1H5a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2h22a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm0 22H5V6h6v1a1 1 0 0 0 2 0V6h6v1a1 1 0 0 0 2 0V6h6z'
    />
    <path d='M20.19 11.41L14.9 18.7l-3.3-2.5a1 1 0 0 0-1.2 1.6l4.1 3.11a1 1 0 0 0 .61.2h.14a1 1 0 0 0 .67-.4l5.89-8.11a1 1 0 1 0-1.62-1.18z'
    />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
