// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M16 3A11.66 11.66 0 0 0 5.8 8.51V5.85a1 1 0 0 0-2 0v5.53a1 1 0 0 0 1 1h4.8a1 1 0 0 0 0-2H7A9.71 9.71 0 0 1 16 5 11 11 0 1 1 5 16a1 1 0 0 0-2 0A13 13 0 1 0 16 3z'
    />
    <path d='M16 7.8a1 1 0 0 0-1 1v6.37a1.91 1.91 0 1 0 2.55 2.75h3.25a1 1 0 0 0 0-2h-3.1a1.87 1.87 0 0 0-.7-.75V8.8a1 1 0 0 0-1-1z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
