// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M27.35 19.22a1 1 0 0 0-1.29.59A10.89 10.89 0 1 1 15.87 5a10.76 10.76 0 0 1 6.36 2.08A4 4 0 1 0 25 6a3.86 3.86 0 0 0-.84.09 12.64 12.64 0 0 0-8.29-3 13 13 0 1 0 12.07 17.42 1 1 0 0 0-.59-1.29z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
