// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react';
import GenerateComponentForGraphic from './template';

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M16 11c1.875 0 3.4 1.525 3.4 3.4 0 1.527-1.018 2.807-2.407 3.235a.96.96 0 0 1-.179.512c-.035.055-.06.116-.104.163-.046.044-.106.068-.159.103A.98.98 0 0 1 16 18.6a.969.969 0 0 1-.482-.141c-.08-.044-.162-.086-.228-.149-.047-.049-.073-.113-.11-.17a.975.975 0 0 1-.18-.54v-.8a1 1 0 0 1 1-1c.772 0 1.4-.628 1.4-1.4 0-.772-.628-1.4-1.4-1.4-.772 0-1.4.628-1.4 1.4a1 1 0 0 1-2 0c0-1.875 1.525-3.4 3.4-3.4zm.71 9.29c.18.19.29.45.29.71 0 .13-.03.26-.08.38s-.12.23-.21.33c-.19.18-.45.29-.71.29-.271 0-.521-.11-.71-.29-.09-.1-.16-.21-.21-.33A.838.838 0 0 1 15 21c0-.26.109-.52.29-.71.37-.37 1.05-.37 1.42 0zM26 21.412l-10 5.462-10-5.462V10.588l10-5.462 10 5.462v10.824zm1.435-12.32l-10.91-5.958a1.096 1.096 0 0 0-1.05 0L4.565 9.092a1.084 1.084 0 0 0-.565.95v11.916c0 .396.217.759.565.95l10.91 5.958a1.096 1.096 0 0 0 1.05 0l10.91-5.958c.348-.191.565-.554.565-.95V10.042c0-.396-.217-.759-.565-.95z' />
  </svg>
);

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic);
