// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from "react"
import GenerateComponentForGraphic from "./template"

// Direct access to SVG
export const Graphic = (
  <svg width="32" height="32" xmlns="http://www.w3.org/2000/svg">
    <path d="M16.993 17.635a.967.967 0 0 1-.179.513c-.035.054-.06.115-.104.162-.046.044-.107.068-.159.103a.976.976 0 0 1-.55.187.976.976 0 0 1-.484-.141c-.079-.044-.16-.086-.227-.15-.047-.048-.073-.112-.11-.17a.975.975 0 0 1-.18-.54v-.8a1 1 0 0 1 1-1 1.4 1.4 0 0 0 1.4-1.4 1.402 1.402 0 0 0-2.8 0 1 1 0 1 1-2 0c0-1.873 1.525-3.4 3.4-3.4s3.4 1.527 3.4 3.4c0 1.528-1.018 2.808-2.407 3.236m-.073 3.745c-.05.12-.12.23-.21.33-.19.18-.45.29-.71.29-.27 0-.52-.11-.71-.29-.09-.1-.16-.21-.21-.33A.826.826 0 0 1 15 21c0-.26.11-.52.29-.71.37-.37 1.05-.37 1.42 0 .18.19.29.45.29.71 0 .13-.03.26-.08.38M27.434 9.093L16.525 3.135a1.09 1.09 0 0 0-1.05 0L4.564 9.093c-.348.19-.565.554-.565.949v11.917c0 .395.217.759.565.949l10.91 5.958c.327.179.723.179 1.05 0l10.91-5.958c.348-.19.565-.554.565-.95V10.043c0-.395-.217-.76-.566-.95" />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
