// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M15 21a1 1 0 0 1-.6-.2l-4-3a1 1 0 0 1 1.2-1.6l3.2 2.4 5.4-7.2a1 1 0 1 1 1.6 1.2l-6 8a1 1 0 0 1-.8.4z'
    />
    <path d='M16 29a1 1 0 0 1-.48-.12l-11-6A1 1 0 0 1 4 22V10a1 1 0 0 1 .52-.88l11-6a1 1 0 0 1 1 0l11 6A1 1 0 0 1 28 10v12a1 1 0 0 1-.52.88l-11 6A1 1 0 0 1 16 29zM6 21.41l10 5.45 10-5.45V10.59L16 5.14 6 10.59zM27 22z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
