// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M26.43 6h-1.3L10.32 2a1 1 0 0 0-1.25 1v3h-1.5A2.6 2.6 0 0 0 5 8.64V12H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h1v3.36A2.6 2.6 0 0 0 7.57 26h18.86A2.6 2.6 0 0 0 29 23.36V8.64A2.6 2.6 0 0 0 26.43 6zM11.07 4.3L17.4 6h-6.33zM5 14h6v4H5zm22 9.36a.61.61 0 0 1-.57.64H7.57a.61.61 0 0 1-.57-.64V20h5a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1H7V8.64A.61.61 0 0 1 7.57 8h18.86a.61.61 0 0 1 .57.64z'
    />
    <path d='M8.92 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2z' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
