// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M16 14.58579l3.2929-3.2929c.39052-.39052 1.02368-.39052 1.4142 0 .39053.39053.39053 1.0237 0 1.41422L17.41422 16l3.2929 3.2929c.39052.39052.39052 1.02368 0 1.4142-.39053.39053-1.0237.39053-1.41422 0L16 17.41422l-3.2929 3.2929c-.39052.39052-1.02368.39052-1.4142 0-.39053-.39053-.39053-1.0237 0-1.41422L14.58578 16l-3.2929-3.2929c-.39052-.39052-.39052-1.02368 0-1.4142.39053-.39053 1.0237-.39053 1.41422 0L16 14.58578zM28 16c0 6.62695-5.37338 12-12 12-6.62795 0-12-5.37238-12-12C4 9.37172 9.37172 4 16 4c6.62695 0 12 5.37238 12 12zm-2 0c0-5.523-4.47757-10-10-10-5.52372 0-10 4.47628-10 10 0 5.52307 4.47664 10 10 10 5.52207 0 10-4.47764 10-10z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
