// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M15.292 21.7061c.092.093.203.166.326.217.122.051.252.077.382.077s.26-.027.382-.077c.123-.051.234-.125.326-.217l4.998-4.988c.392-.391.392-1.024.002-1.414-.391-.393-1.023-.391-1.414-.002L17 18.5891V5.0001c0-.553-.447-1-1-1-.553 0-1 .447-1 1v13.589l-3.294-3.287c-.391-.389-1.023-.391-1.414.002-.39.39-.39 1.023.002 1.414l4.998 4.988zM28 20.0101v6c0 1.102-.897 2-2 2H6c-1.103 0-2-.898-2-2v-6c0-.553.447-1 1-1 .553 0 1 .447 1 1v6h20v-6c0-.553.447-1 1-1 .553 0 1 .447 1 1z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
