import { StyledComponentClass } from 'styled-components';
export { default as ArrowRightIcon } from './arrow';
export { default as AlertCirlceIcon } from './alert-cirlce';
export { default as CaratIcon } from './carat';
export { default as CheckCircleIcon } from './check-circle';
export { default as CloseCircleIcon } from './close-circle';
export { default as CheckIcon } from './check';
export { default as CloseStrokeIcon } from './close-stroke';
export { default as DownloadIcon } from './download';
export { default as EmoteSadIcon } from './emote-sad';
export { default as EmoteSmileIcon } from './emote-smile';
export { default as LogoYoutubeIcon } from './logo-youtube';
export { default as PaymentDueIcon } from './payment-due';
export { default as PrintIcon } from './print';
export { default as RefreshIcon } from './refresh';
export { default as SettingsAdvancedIcon } from './settings-advanced';
export { default as SettingsIcon } from './settings';
export { default as ThumbsUpIcon } from './thumbs-up';
export { default as VerifiedFillIcon } from './verified-fill';
export { default as VerifiedIcon } from './verified';
export { default as WalletActivityIcon } from './wallet-activity';
export { default as WalletAddIcon } from './wallet-add';
export { default as WalletBackupIcon } from './wallet-backup';
export { default as WalletImportIcon } from './wallet-import';
export { default as WalletManageIcon } from './wallet-manage';
export { default as UpholdSystemIcon } from './uphold-system';
export { default as BatColorIcon } from './bat-color';
export { default as BatGreyIcon } from './bat-grey';
export { default as UpholdColorIcon } from './uphold-color';
export declare const ArrowDownIcon: StyledComponentClass<any, any, any>;
export declare const ArrowLeftIcon: StyledComponentClass<any, any, any>;
export declare const ArrowUpIcon: StyledComponentClass<any, any, any>;
export declare const CaratDownIcon: StyledComponentClass<any, any, any>;
export declare const CaratLeftIcon: StyledComponentClass<any, any, any>;
export declare const CaratUpIcon: StyledComponentClass<any, any, any>;
export declare const ThumbsDownIcom: any;
