"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var arrow_1 = require("./arrow");
exports.ArrowRightIcon = arrow_1.default;
var alert_cirlce_1 = require("./alert-cirlce");
exports.AlertCirlceIcon = alert_cirlce_1.default;
var carat_1 = require("./carat");
exports.CaratIcon = carat_1.default;
var check_circle_1 = require("./check-circle");
exports.CheckCircleIcon = check_circle_1.default;
var close_circle_1 = require("./close-circle");
exports.CloseCircleIcon = close_circle_1.default;
var check_1 = require("./check");
exports.CheckIcon = check_1.default;
var close_stroke_1 = require("./close-stroke");
exports.CloseStrokeIcon = close_stroke_1.default;
var download_1 = require("./download");
exports.DownloadIcon = download_1.default;
var emote_sad_1 = require("./emote-sad");
exports.EmoteSadIcon = emote_sad_1.default;
var emote_smile_1 = require("./emote-smile");
exports.EmoteSmileIcon = emote_smile_1.default;
var logo_youtube_1 = require("./logo-youtube");
exports.LogoYoutubeIcon = logo_youtube_1.default;
var payment_due_1 = require("./payment-due");
exports.PaymentDueIcon = payment_due_1.default;
var print_1 = require("./print");
exports.PrintIcon = print_1.default;
var refresh_1 = require("./refresh");
exports.RefreshIcon = refresh_1.default;
var settings_advanced_1 = require("./settings-advanced");
exports.SettingsAdvancedIcon = settings_advanced_1.default;
var settings_1 = require("./settings");
exports.SettingsIcon = settings_1.default;
var thumbs_up_1 = require("./thumbs-up");
exports.ThumbsUpIcon = thumbs_up_1.default;
var verified_fill_1 = require("./verified-fill");
exports.VerifiedFillIcon = verified_fill_1.default;
var verified_1 = require("./verified");
exports.VerifiedIcon = verified_1.default;
var wallet_activity_1 = require("./wallet-activity");
exports.WalletActivityIcon = wallet_activity_1.default;
var wallet_add_1 = require("./wallet-add");
exports.WalletAddIcon = wallet_add_1.default;
var wallet_backup_1 = require("./wallet-backup");
exports.WalletBackupIcon = wallet_backup_1.default;
var wallet_import_1 = require("./wallet-import");
exports.WalletImportIcon = wallet_import_1.default;
var wallet_manage_1 = require("./wallet-manage");
exports.WalletManageIcon = wallet_manage_1.default;
var uphold_system_1 = require("./uphold-system");
exports.UpholdSystemIcon = uphold_system_1.default;
var bat_color_1 = require("./bat-color");
exports.BatColorIcon = bat_color_1.default;
var bat_grey_1 = require("./bat-grey");
exports.BatGreyIcon = bat_grey_1.default;
var uphold_color_1 = require("./uphold-color");
exports.UpholdColorIcon = uphold_color_1.default;
function RotatedIconComponent(iconComponent, degrees) {
    return iconComponent.extend `
    transform: rotate(${degrees}deg);
  `;
}
const arrow_2 = require("./arrow");
exports.ArrowDownIcon = RotatedIconComponent(arrow_2.default, 90);
exports.ArrowLeftIcon = RotatedIconComponent(arrow_2.default, 180);
exports.ArrowUpIcon = RotatedIconComponent(arrow_2.default, -90);
const carat_2 = require("./carat");
exports.CaratDownIcon = RotatedIconComponent(carat_2.default, 90);
exports.CaratLeftIcon = RotatedIconComponent(carat_2.default, 180);
exports.CaratUpIcon = RotatedIconComponent(carat_2.default, -90);
const thumbs_up_2 = require("./thumbs-up");
exports.ThumbsDownIcom = thumbs_up_2.default.extend `
  transform: scaleY(-1);
`;
//# sourceMappingURL=index.js.map