// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M26 6c.553 0 1 .448 1 1v20c0 .552-.447 1-1 1H6c-.553 0-1-.448-1-1V7c0-.552.447-1 1-1h5V5c0-.552.447-1 1-1 .553 0 1 .448 1 1v1h6V5c0-.552.447-1 1-1 .553 0 1 .448 1 1v1h5zM7 26h18V12H7v14zm4-18c0 .552.447 1 1 1 .553 0 1-.448 1-1h6c0 .552.447 1 1 1 .553 0 1-.448 1-1h4v2H7V8h4zm5 9c-.33 0-.6.224-.6.5s.27.5.6.5c1.6548 0 3 1.122 3 2.5 0 1.022-.7416 1.901-1.8 2.288V23c0 .552-.5364 1-1.2 1s-1.2-.448-1.2-1h-.6c-.6636 0-1.2-.448-1.2-1s.5364-1 1.2-1H16c.33 0 .6-.224.6-.5s-.27-.5-.6-.5c-1.6548 0-3-1.122-3-2.5 0-1.022.7416-1.901 1.8-2.288V15c0-.552.5364-1 1.2-1s1.2.448 1.2 1h.6c.6636 0 1.2.448 1.2 1s-.5364 1-1.2 1H16z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
