// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M21.1997 17c-.551 0-1-.448-1-1s.449-1 1-1c.551 0 1 .448 1 1s-.449 1-1 1m5.8-2h-2.984c-.414-1.162-1.514-2-2.816-2-1.302 0-2.402.838-2.816 2H4.9997c-.552 0-1 .448-1 1s.448 1 1 1h13.384c.415 1.162 1.514 2 2.816 2 1.302 0 2.402-.838 2.816-2h2.984c.553 0 1-.448 1-1s-.447-1-1-1m-16 11c-.551 0-1-.448-1-1s.449-1 1-1c.552 0 1 .448 1 1s-.448 1-1 1m16-2h-13.184c-.414-1.162-1.514-2-2.816-2-1.301 0-2.401.838-2.816 2h-3.184c-.552 0-1 .448-1 1s.448 1 1 1h3.185c.414 1.162 1.514 2 2.815 2 1.302 0 2.402-.838 2.816-2h13.184c.553 0 1-.448 1-1s-.447-1-1-1m-12.8-18c.551 0 1 .448 1 1s-.449 1-1 1c-.551 0-1-.448-1-1s.449-1 1-1m-9.2 2h6.384c.415 1.162 1.514 2 2.816 2 1.302 0 2.402-.838 2.816-2h9.984c.553 0 1-.448 1-1s-.447-1-1-1h-9.984c-.414-1.162-1.514-2-2.816-2-1.302 0-2.402.838-2.816 2h-6.384c-.552 0-1 .448-1 1s.448 1 1 1'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
