// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M25.571 6C26.91 6 28 7.101 28 8.455V17c0 .552-.447 1-1 1-.553 0-1-.448-1-1V8.455c0-.247-.196-.455-.429-.455H8.429C8.196 8 8 8.208 8 8.455V12h5.001c.553 0 1 .448 1 1v4c0 .552-.447 1-1 1H8v3.545c0 .247.196.455.429.455H17c.553 0 1 .448 1 1s-.447 1-1 1H8.429C7.09 24 6 22.899 6 21.545V18H5c-.553 0-1-.448-1-1v-4c0-.552.447-1 1-1h1V8.455C6 7.101 7.09 6 8.429 6h17.142zM6 16h6.001v-2H6v2zm16 3c-.553 0-1-.448-1-1s.447-1 1-1h1c.553 0 1 .448 1 1s-.447 1-1 1h-1zm2 5c.553 0 1 .448 1 1s-.447 1-1 1h-2c-.553 0-1-.448-1-1s.447-1 1-1v-2c-.553 0-1-.448-1-1s.447-1 1-1h1c.553 0 1 .448 1 1v3z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
