// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg width='27' height='32' xmlns='http://www.w3.org/2000/svg'>
  <path d='M26.667 6.649v4.003c0 .738-.007 1.945-.015 2.683-.001.139-.295 14.01-12.863 18.584-.009.003-.018.003-.028.005a1.29 1.29 0 0 1-.428.076c-.148 0-.292-.028-.429-.076-.008-.002-.017-.002-.027-.005C.31 27.345.016 13.474.015 13.335.007 12.597 0 11.39 0 10.652V6.649A2.67 2.67 0 0 1 2.667 3.98H4c5.6 0 8.121-3.314 8.225-3.455a1.315 1.315 0 0 1 1.027-.52c.452-.038.91.131 1.193.526.1.135 2.622 3.45 8.222 3.45H24a2.67 2.67 0 0 1 2.667 2.668zM13.333 9.985c-.736 0-1.333.596-1.333 1.334v5.337a1.333 1.333 0 1 0 2.667 0v-5.337c0-.738-.598-1.334-1.334-1.334zm.947 9.727c.24.252.387.6.387.947 0 .173-.027.347-.107.507a1.56 1.56 0 0 1-.28.44 1.325 1.325 0 0 1-.947.387c-.36 0-.693-.135-.946-.387a1.56 1.56 0 0 1-.28-.44 1.12 1.12 0 0 1-.107-.507c0-.347.147-.695.387-.947a1.36 1.36 0 0 1 1.453-.28c.173.066.307.16.44.28z' fillRule='evenodd' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
