// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M26 8.99v3L25.99 14c0 0.1-0.22 10.5-9.65 13.94h-0.02a0.97 0.97 0 0 1-0.64 0h-0.02C6.23 24.5 6 14.1 6 14A225 225 0 0 1 6 12v-3a2 2 0 0 1 2-2h1c4.2 0 6.1-2.5 6.17-2.6A0.99 0.99 0 0 1 15.94 4a0.98 0.98 0 0 1 0.9 0.4C16.9 4.5 18.8 6.99 23 6.99h1a2 2 0 0 1 2 2zM16 10a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0v-4a1 1 0 0 0-1-1zm0.71 8.29a1.03 1.03 0 0 0-1.42 0 1.05 1.05 0 0 0-0.29 0.7 0.84 0.84 0 0 0 0.08 0.39 1.17 1.17 0 0 0 0.21 0.33A1 1 0 0 0 16 20a1 1 0 0 0 0.71-0.3 1.17 1.17 0 0 0 0.21-0.32A0.84 0.84 0 0 0 17 19a1.05 1.05 0 0 0-0.29-0.71z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
