// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M7.24134 15H27c.55228 0 1 .44772 1 1s-.44772 1-1 1H7.24134l6.78743 6.26519c.40582.3746.43113 1.00726.05653 1.41308-.3746.40583-1.00725.43114-1.41308.05654l-8.136-7.51c-.71497-.65997-.71497-1.78965 0-2.44962l8.136-7.51c.40583-.3746 1.03848-.34929 1.41308.05654.3746.40582.3493 1.03848-.05653 1.41308L7.24134 15z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
