// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M12 2C6.47714 2 2 6.47714 2 12s4.47714 10 10 10 10-4.47714 10-10S17.52286 2 12 2zM5.84133 18.15867c-3.25089-3.25089-3.3931-8.42569-.43952-11.84448l12.28404 12.284c-3.41952 2.95419-8.59428 2.81072-11.84452-.43952zm12.75686-.47286l-12.284-12.284c3.41952-2.95415 8.59424-2.81068 11.84448.43952 3.25089 3.25085 3.3931 8.42569.43952 11.84448z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
