// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M12 2C6.47714 2 2 6.47714 2 12s4.47714 10 10 10 10-4.47714 10-10S17.52286 2 12 2zm5.70246 4.29754c2.95064 2.9506 3.10685 7.55246.6437 10.68004L7.02243 5.65383c3.12855-2.46391 7.7302-2.30617 10.68004.64371zM6.29754 17.70246C3.3469 14.75186 3.19069 10.15 5.65384 7.02242l11.32374 11.32375c-3.12855 2.46391-7.7302 2.30617-10.68004-.64371z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
