// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M12 2C6.47718 2 2 6.47714 2 12s4.47718 10 10 10 10-4.47718 10-10S17.52286 2 12 2zm5.24629 4.75371c2.63903 2.63903 2.82258 6.67262.83375 9.5015L7.74476 5.92c2.8308-1.99016 6.86395-1.80383 9.50153.83371zM6.75371 17.24629c-2.63903-2.63903-2.82258-6.67262-.83375-9.5015L16.25524 18.08c-2.83076 1.99016-6.86395 1.80387-9.50153-.83371z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
