// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
	<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
		<path d='M26.147 23.296A9.961 9.961 0 0 0 26.203 27H27a1 1 0 0 1 0 2H8.056C5.819 29 4 27.215 4 25V6.153C4 4.392 5.509 3 7.334 3h17.842C26.178 3 27 3.8 27 4.803V21a1 1 0 0 1 0 2h-.28a.998.998 0 0 1-.573.296zM24.17 23H8.056C6.915 23 6 23.898 6 25c0 1.102.915 2 2.056 2h16.112a11.954 11.954 0 0 1 0-4zM6 21.55A4.083 4.083 0 0 1 8.056 21H25V5h-4v9a1 1 0 0 1-1.634.773L16 12.012l-3.366 2.761A1 1 0 0 1 11 14V5H7.334C6.579 5 6 5.534 6 6.152v15.399zM13 5v6.886l2.366-1.94a1 1 0 0 1 1.268 0L19 11.885V5h-6z'
		/>
	</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
