// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M5.5 5.05296v13.95016c0 2.6542 3.23125 4 5.11875 2.11214l7-6.97196c1.16875-1.1651 1.16875-3.05919 0-4.23053l-7-6.9782C8.7375 1.06543 5.5 2.39253 5.5 5.05297zm10 6.9782l-7 6.97819V5.05295l7 6.9782z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
