// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M19.998 6H4.00237C2.22582 6 1.32945 8.1555 2.5882 9.41419l7.99762 8c.781.781 2.04738.78106 2.82844 0l7.998-8C22.66844 8.158 21.77812 6 19.998 6zM12 16L4 8h16l-8 8z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
