// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M18.94704 6H4.99688c-2.6542 0-4 3.23125-2.11214 5.11875l6.97196 7c1.1651 1.16875 3.05919 1.16875 4.23053 0l6.9782-7C22.93457 9.2375 21.60747 6 18.94703 6zm-6.9782 10L4.99066 9h13.9564l-6.9782 7z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
