// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M16.58579 16l-3.2929-3.2929c-.39052-.39052-.39052-1.02368 0-1.4142.39053-.39053 1.0237-.39053 1.41422 0l4 4c.39052.39052.39052 1.02368 0 1.4142l-4 4c-.39053.39053-1.0237.39053-1.41422 0-.39052-.39052-.39052-1.02368 0-1.4142L16.5858 16z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
