// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M5.05296 18h13.95016c2.6542 0 4-3.23125 2.11214-5.11875l-6.97196-7c-1.1651-1.16875-3.05919-1.16875-4.23053 0l-6.9782 7C1.06543 14.7625 2.39253 18 5.05297 18zm6.9782-10l6.97819 7H5.05295l6.9782-7z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
