// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M13.06676 25.00001c-.263 0-.517-.104-.704-.29l-8.067-8c-.392-.389-.395-1.022-.005-1.414.387-.392 1.021-.395 1.414-.006l7.309 7.249 13.233-15.196c.361-.416.993-.46 1.41-.097.417.363.46.994.098 1.411l-13.934 16c-.181.208-.441.332-.717.342-.013.001-.025.001-.037.001'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
