// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='26' height='26' version='1' xmlns='http://www.w3.org/2000/svg'>
    <path d='M24 23l-1 1H12l-1-1v-3h3c2 0 3-1 3-3V8h6l1 1v14zM2 17V3l1-1h11l1 1v14l-1 1H3l-1-1zM23 6h-6V3c0-2-1-3-3-3H3C1 0 0 1 0 3v14c0 2 1 3 3 3h6v3c0 2 1 3 3 3h11c2 0 3-1 3-3V9c0-2-1-3-3-3z' fill='#373843' fillRule='evenodd' />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
