// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M24.839 11.404L20.596 7.16 8.222 19.536l4.243 4.242 12.374-12.374zm1.414-1.414l.354-.354a3 3 0 1 0-4.243-4.243l-.353.354 4.242 4.243zM12.475 26.597a.995.995 0 0 1-.513.281l-7.02 1.466a1 1 0 0 1-1.187-1.167l1.363-7.122c.04-.21.143-.39.285-.529L20.95 3.98a5 5 0 0 1 7.07 7.071L12.476 26.597zm-1.563-1.543l-3.957-3.957-.953 4.982 4.91-1.025z'
    />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
