// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

export const Graphic = (
  <svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <defs>
      <radialGradient cx='169.267%' cy='115.927%' fx='169.267%' fy='115.927%' r='205.642%' gradientTransform='matrix(-.82312 -.56373 .5618 -.82596 2.435 3.071)'>
        <stop stopColor='#FB542B' offset='0%'/>
        <stop stopColor='#A91B78' offset='45.714%'/>
        <stop stopColor='#392DD1' offset='100%'/>
      </radialGradient>
    </defs>
    <path d='M24.602 31.948c-4.073 0-7.386-3.313-7.386-7.385 0-4.071 3.313-7.384 7.386-7.384 4.071 0 7.383 3.313 7.383 7.384 0 4.072-3.312 7.385-7.383 7.385zm0-12.307a4.928 4.928 0 0 0-4.924 4.922 4.929 4.929 0 0 0 4.924 4.923 4.928 4.928 0 0 0 4.922-4.923 4.927 4.927 0 0 0-4.922-4.922zm-1.232 4.922V20.87h2.462v2.462h2.461v2.462H23.37v-1.23zm5.028-9.692a1.219 1.219 0 0 1-1.337-1.115 12.422 12.422 0 0 0-.536-2.571h-3.486c.154.782.28 1.572.335 2.379a1.23 1.23 0 0 1-1.144 1.312l-.084.003a1.231 1.231 0 0 1-1.228-1.146 16.22 16.22 0 0 0-.391-2.548h-4.492v17.23a1.23 1.23 0 0 1-1.231 1.23c-8.144 0-14.77-6.624-14.77-14.769C.035 6.732 6.66.107 14.805.107c7.696 0 14.02 5.773 14.709 13.429a1.23 1.23 0 0 1-1.115 1.335zM13.273 21.03H9.567a16.888 16.888 0 0 0 3.706 5.584V21.03zm-3.666 5.132a19.174 19.174 0 0 1-2.682-5.132h-3.04c1.318 2.258 3.307 4.08 5.722 5.132zm-7.11-11.286c0 1.288.202 2.526.57 3.693h3.5a18.922 18.922 0 0 1-.378-3.69c0-1.252.139-2.485.38-3.694H3.067a12.242 12.242 0 0 0-.57 3.691zm1.69-6.153h3.04a19.183 19.183 0 0 1 2.686-5.135C7.494 4.64 5.503 6.462 4.186 8.723zm9.386-5.577A16.895 16.895 0 0 0 9.87 8.723h3.703V3.146zm-4.48 8.039a16.17 16.17 0 0 0-.443 3.694c0 1.254.161 2.489.442 3.69h4.481v-7.384h-4.48zm6.942-2.462h3.713a16.771 16.771 0 0 0-3.713-5.59v5.59zM19.68 3.57a19.009 19.009 0 0 1 2.688 5.152h3.098A12.214 12.214 0 0 0 19.68 3.57z' transform='translate(-.003 .041)' fill='url(#a)' fillRule='nonzero'/>
  </svg>
)

export default GenerateComponentForGraphic(Graphic)
