// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

export const Graphic = (
  <svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <defs>
      <radialGradient cx='169.267%' cy='115.927%' fx='169.267%' fy='115.927%' r='205.16%' id='a'>
        <stop stopColor='#FB542B' offset='0%'/>
        <stop stopColor='#A91B78' offset='45.714%'/>
        <stop stopColor='#392DD1' offset='100%'/>
      </radialGradient>
    </defs>
    <path d='M16 0c8.837 0 16 7.163 16 16s-7.163 16-16 16S0 24.837 0 16 7.163 0 16 0zm0 2.667C8.636 2.667 2.667 8.637 2.667 16c0 7.364 5.97 13.333 13.333 13.333 7.364 0 13.333-5.97 13.333-13.333 0-7.364-5.97-13.333-13.333-13.333zm0 5.948c.68 0 1.23.551 1.23 1.231l.001 5.253c.374.216.685.527.901.901h6.483a1.23 1.23 0 0 1 0 2.462h-6.483a2.46 2.46 0 0 1-4.594-1.231 2.46 2.46 0 0 1 1.231-2.132V9.846c0-.68.551-1.23 1.231-1.23z' fill='url(#a)' fillRule='nonzero'/>
  </svg>
)

export default GenerateComponentForGraphic(Graphic)
