// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg' xmlnsXlink='http://www.w3.org/1999/xlink'>
    <defs>
        <path id='rewards-a' d='M.003.032h23.21V23H.002z' />
    </defs>
    <g fill='none' fillRule='evenodd'>
        <g transform='translate(6.755 4.5)'>
            <mask id='rewards-b' fill='#fff'>
                <use xlinkHref='#rewards-a' />
            </mask>
            <path d='M22.157 16.214a.525.525 0 0 1-.527.522h-3.693a2.1 2.1 0 0 1-2.11-2.088c0-1.151.946-2.088 2.11-2.088h3.693c.29 0 .527.234.527.522v3.132zm-2.11 5.742H2.11a1.051 1.051 0 0 1-1.055-1.044V8.384c0-.575.474-1.044 1.055-1.044h17.937c.582 0 1.055.469 1.055 1.044v3.132h-3.165c-1.746 0-3.166 1.405-3.166 3.132s1.42 3.132 3.166 3.132h3.165v3.132a1.05 1.05 0 0 1-1.055 1.044zm-5.195-20.74a1.03 1.03 0 0 1 .783-.105c.27.072.495.244.634.485l.001.002-8.156 4.698H6.031l8.82-5.08zm2.987 3.094l1.15 1.986H14.39l3.448-1.986zm-7.628 1.986l6.583-3.792.521.9-5.021 2.892H10.21zm11.946 5.316V8.384c0-1.094-.858-1.984-1.942-2.07l-3.03-5.237a2.082 2.082 0 0 0-1.277-.974 2.092 2.092 0 0 0-1.587.21L3.934 6.296H2.11C.946 6.296 0 7.233 0 8.384v12.528A2.1 2.1 0 0 0 2.11 23h17.937a2.1 2.1 0 0 0 2.11-2.088v-3.228a1.565 1.565 0 0 0 1.055-1.47v-3.132c0-.68-.442-1.253-1.055-1.47z'
            fill='#A1A8F2' mask='url(#rewards-b)' />
        </g>
        <path d='M24.132 18.176a.939.939 0 0 0-.943.932c0 .514.423.933.943.933s.942-.419.942-.933a.939.939 0 0 0-.942-.932'
        fill='#A1A8F2' />
        <g transform='translate(2 8.682)'>
            <ellipse fill='#1BBA6A' cx='6.34' cy='6.273' rx='6.34' ry='6.273' />
            <path fill='#FFF' d='M2.635 6.502l.462-.729 2.583 1.51 3.968-3.307.517.694L5.68 9.827z'
            />
        </g>
    </g>
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
