// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <g transform='translate(2 2)' fill='none' fillRule='evenodd'>
        <circle fill='#FFF' cx='14' cy='14' r='14' />
        <path fill='#A1A8F2' d='M5.818 14.512l1.02-1.627 5.704 3.37 8.764-7.381 1.143 1.548-9.907 11.511z'
        />
    </g>
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
