// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

export const Graphic = (
  <svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <defs>
      <radialGradient cx='169.267%' cy='115.927%' fx='169.267%' fy='115.927%' r='205.16%' id='a'>
        <stop stopColor='#FB542B' offset='0%'/>
        <stop stopColor='#A91B78' offset='45.714%'/>
        <stop stopColor='#392DD1' offset='100%'/>
      </radialGradient>
    </defs>
    <path d='M31.981 15.396l-1.732 13.525C30.057 30.637 28.521 32 26.753 32H16c-1.383 0-3.232-.66-4.301-1.533l-2.364-1.943v.81c0 .735-.597 1.333-1.334 1.333H1.334A1.334 1.334 0 0 1 0 29.333V12c0-.736.597-1.333 1.334-1.333H8c.737 0 1.334.597 1.334 1.333h1.662c.503-2.497 1.67-8.241 1.964-9.165C13.48 1.192 15.17 0 16.98 0c2.4 0 4.353 1.915 4.353 4.267V12h7.584c.895 0 1.74.37 2.318 1.016.572.639.843 1.507.747 2.38zM6.667 13.333h-4V28h4V13.333zm22.579 1.46c-.074-.082-.189-.126-.33-.126H19.91a1.334 1.334 0 0 1-1.333-1.334c0-.21.06-.404.147-.581V4.555c-.022-.096-.058-.186-.058-.288 0-.852-.79-1.6-1.687-1.6-.655 0-1.303.428-1.477.973-.234.739-1.416 6.497-2.106 9.955a1.334 1.334 0 0 1-1.308 1.072H9.334v10.406l4.054 3.33c.593.486 1.84.93 2.611.93h10.754c.395 0 .806-.354.848-.729l1.731-13.524a.365.365 0 0 0-.086-.287z' fill='url(#a)' fillRule='nonzero'/>
  </svg>
)

export default GenerateComponentForGraphic(Graphic)
