// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M28 25H4V7h8.199l3.2 2.408c.042.031.09.046.135.071.038.02.072.043.113.059a1 1 0 0 0 .352.071H28V25zm0-17.391H16.334l-3.2-2.408c-.031-.024-.07-.03-.104-.05a.935.935 0 0 0-.183-.088 1.01 1.01 0 0 0-.201-.041c-.039-.004-.073-.022-.113-.022H4c-1.103 0-2 .897-2 2v18c0 1.103.897 2 2 2h24c1.103 0 2-.897 2-2V9.609c0-1.103-.897-2-2-2z'/>
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
