// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M3 18a1 1 0 0 1 2 0v9a1 1 0 0 1-2 0v-9zm4 4a1 1 0 0 1 2 0v5a1 1 0 0 1-2 0v-5zm4-5a1 1 0 0 1 2 0v10a1 1 0 0 1-2 0V17zm4 3a1 1 0 0 1 2 0v7a1 1 0 0 1-2 0v-7zm4-4a1 1 0 0 1 2 0v11a1 1 0 0 1-2 0V16zm4 2a1 1 0 0 1 2 0v9a1 1 0 0 1-2 0v-9zm4-5a1 1 0 0 1 2 0v14a1 1 0 0 1-2 0V13zM8.825 15.566A1 1 0 0 1 7.4 15.8l-4-3a1 1 0 1 1 1.2-1.6l3.165 2.374 3.41-4.971a1 1 0 0 1 1.241-.344l3.29 1.507 3.513-4.39a1 1 0 0 1 1.562 0l3.08 3.85 3.27-5.722a1 1 0 1 1 1.737.992l-4 7a1 1 0 0 1-1.649.129L20 7.6l-3.22 4.024a1 1 0 0 1-1.196.284l-3.235-1.48-3.524 5.137z'
    />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
