// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M20.06238 4.16496c-2.12476-1.76072-5.30215-1.46853-7.27486.51227l-.76803.7741-.76803-.7703c-1.59064-1.60134-4.79922-2.56518-7.27485-.51607-2.44834 2.03392-2.577 5.68437-.38597 7.88526l7.54386 7.5817c.24172.24286.5614.36808.8811.36808.31968 0 .63937-.12143.88109-.36808l7.54386-7.5817c2.19883-2.20089 2.07017-5.85134-.37817-7.88526zm-.51072 7.04285l-7.51657 7.5817-7.54776-7.5817c-1.49708-1.50268-1.80897-4.36763.3002-6.11696 2.13645-1.7759 4.64717-.48951 5.56725.43638l1.66471 1.67344 1.66472-1.67344c.90448-.91071 3.4386-2.2009 5.56725-.43638 2.10527 1.74553 1.79727 4.61049.3002 6.11696z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
