// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M19.90625 4.332c-2.25781-1.944-5.7461-1.652-7.90625.6-2.16016-2.252-5.64844-2.548-7.90625-.6-2.9375 2.532-2.50781 6.66-.41406 8.848l6.85156 7.148c.39063.408.91406.636 1.46875.636.5586 0 1.07813-.224 1.46875-.632l6.85156-7.148c2.08985-2.188 2.52735-6.316-.41406-8.852zm-.92188 7.5l-6.85156 7.148c-.09375.096-.17187.096-.26562 0l-6.85157-7.148c-1.42578-1.488-1.71484-4.304.28516-6.028 1.51953-1.308 3.86328-1.112 5.33203.42L12 7.652l1.36719-1.428c1.47656-1.54 3.82031-1.728 5.33203-.424 1.9961 1.724 1.69922 4.556.28515 6.032z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
