// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M20.06238 4.26682c-2.13645-1.87217-5.31384-1.53542-7.27486.5452l-.76803.81382-.76803-.81381c-1.95711-2.08063-5.1384-2.41738-7.27485-.54521-2.44834 2.14877-2.577 6.00534-.38597 8.33452l7.54386 8.0098c.48733.51715 1.27876.51715 1.76608 0l7.54386-8.0098c2.19494-2.32918 2.06628-6.18575-.38206-8.33452z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
