// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M16 7.2a1 1 0 0 0-1 1v6.945c-.595.347-1 .984-1 1.722A2 2 0 1 0 17.645 18H21.2a1 1 0 0 0 0-2h-3.406a2 2 0 0 0-.794-.855V8.2a1 1 0 0 0-1-1M30 16c0 7.72-6.28 14-14 14S2 23.72 2 16a1 1 0 0 1 2 0c0 6.617 5.383 12 12 12s12-5.383 12-12S22.617 4 16 4c-4.393 0-7.781 2.085-9.855 6h2.922a1 1 0 0 1 0 2h-5.2a1 1 0 0 1-1-1V5a1 1 0 1 1 2 0v3.18C7.327 4.185 11.224 2 16 2c7.72 0 14 6.28 14 14'/>
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
