// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M29 7.55c-.907.468-1.965.78-3.023.935 1.133-.701 1.965-1.793 2.418-3.118-1.058.623-2.192 1.091-3.4 1.325-1.69-1.785-4.319-2.206-6.453-1.033-2.135 1.173-3.263 3.659-2.769 6.1C11.541 11.527 7.46 9.5 4.814 5.99a5.444 5.444 0 0 0-.648 4.022 5.297 5.297 0 0 0 2.31 3.307c-.83 0-1.662-.156-2.418-.546.076 2.573 1.814 4.834 4.233 5.38-.756.234-1.588.234-2.419.078.756 2.261 2.797 3.82 5.064 3.898C8.744 24.001 5.796 24.86 3 24.39c4.767 3.282 10.928 3.484 15.888.52 4.959-2.963 7.855-8.577 7.467-14.476C27.413 9.654 28.32 8.72 29 7.55'
    />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
