// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M19.9795 16c0 .352-.185.677-.485.857l-5 3c-.159.095-.337.143-.515.143-.17 0-.34-.043-.493-.13a.9993.9993 0 0 1-.507-.87v-6c0-.36.193-.692.507-.87.313-.178.698-.173 1.008.013l5 3c.3.18.485.505.485.857m5.216 5.534c-.193.429-.84.935-1.305 1.021-.024.004-2.522.445-7.894.445h-.016c-5.372 0-7.868-.441-7.891-.445-.467-.087-1.115-.591-1.303-1.015-.008-.019-.786-1.853-.786-5.54 0-3.688.778-5.522.784-5.536.191-.429.837-.933 1.303-1.019.025-.004 2.521-.445 7.909-.445 5.372 0 7.87.441 7.893.445.466.086 1.112.591 1.303 1.015.008.018.787 1.853.787 5.54 0 3.687-.779 5.521-.784 5.534m1.824-11.888c-.463-1.031-1.653-1.963-2.769-2.167-.106-.02-2.667-.479-8.27-.479-5.588 0-8.147.459-8.253.479-1.118.205-2.309 1.137-2.769 2.167-.04.088-.958 2.188-.958 6.354s.918 6.265.958 6.351c.459 1.031 1.649 1.963 2.769 2.17.106.02 2.665.479 8.253.479h.016c5.587 0 8.148-.459 8.255-.479 1.117-.206 2.306-1.138 2.768-2.168.039-.087.96-2.187.96-6.353s-.921-6.267-.96-6.354'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
