// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M28 8.91a4.4 4.4 0 0 0-3-2.37A54.4 54.4 0 0 0 16 6a54.26 54.26 0 0 0-9 .54 4.44 4.44 0 0 0-3 2.37A19.4 19.4 0 0 0 3 16a19.4 19.4 0 0 0 1 7.09 4.44 4.44 0 0 0 3 2.37 54.26 54.26 0 0 0 9 .54 54.26 54.26 0 0 0 9-.54 4.4 4.4 0 0 0 3-2.37A19 19 0 0 0 29 16a19 19 0 0 0-1-7.09zm-1.87 13.38a2.45 2.45 0 0 1-1.49 1.21A55 55 0 0 1 16 24a55 55 0 0 1-8.63-.5 2.43 2.43 0 0 1-1.49-1.21A17.8 17.8 0 0 1 5 16a17.8 17.8 0 0 1 .87-6.29A2.43 2.43 0 0 1 7.36 8.5 55.13 55.13 0 0 1 16 8a55 55 0 0 1 8.63.5 2.45 2.45 0 0 1 1.49 1.21A17.8 17.8 0 0 1 27 16a17.8 17.8 0 0 1-.87 6.29z'
    />
    <path d='M20.51 15.09l-7-4a1 1 0 0 0-1 0A1 1 0 0 0 12 12v8a1 1 0 0 0 .5.87 1 1 0 0 0 .5.13 1 1 0 0 0 .5-.13l7-4A1 1 0 0 0 21 16a1 1 0 0 0-.49-.91z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
