// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M12 9.6c1.3802 0 2.5 1.075 2.5 2.4s-1.1198 2.4-2.5 2.4-2.5-1.075-2.5-2.4 1.1198-2.4 2.5-2.4zM9.5 4.4c0 1.325 1.1198 2.4 2.5 2.4s2.5-1.075 2.5-2.4S13.3802 2 12 2 9.5 3.075 9.5 4.4zm0 15.2c0 1.325 1.1198 2.4 2.5 2.4s2.5-1.075 2.5-2.4-1.1198-2.4-2.5-2.4-2.5 1.075-2.5 2.4z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
