// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M12 9.09677c1.65833 0 3 1.2984 3 2.90323 0 1.60484-1.34167 2.90323-3 2.90323S9 13.60483 9 12c0-1.60484 1.34167-2.90323 3-2.90323zM9 4.90323c0 1.60483 1.34167 2.90322 3 2.90322s3-1.29839 3-2.90322C15 3.29839 13.65833 2 12 2S9 3.29839 9 4.90323zm0 14.19354C9 20.70161 10.34167 22 12 22s3-1.29839 3-2.90323c0-1.60483-1.34167-2.90322-3-2.90322s-3 1.29839-3 2.90322z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
