// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>
        <path d='M12 9.89474c1.10625 0 2 .94079 2 2.10526s-.89375 2.10526-2 2.10526S10 13.16447 10 12s.89375-2.10526 2-2.10526zm-2-5.78948c0 1.16448.89375 2.10527 2 2.10527s2-.9408 2-2.10527C14 2.9408 13.10625 2 12 2s-2 .94079-2 2.10526zm0 15.78948C10 21.0592 10.89375 22 12 22s2-.94079 2-2.10526c0-1.16448-.89375-2.10527-2-2.10527s-2 .9408-2 2.10527z'
        />
    </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
