// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M26 26v-8.98a1 1 0 1 1 2 0V27a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h9.37a1 1 0 0 1 0 2H6v20h20zM24.59 6h-5.6a1 1 0 0 1 0-2H27a1 1 0 0 1 1 1v8a1 1 0 0 1-2 0V7.41l-13.3 13.3a1 1 0 0 1-1.4-1.42L24.58 6z'/>
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
