// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
  <svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M19.897 3l-.703.958-5.015 6.836c-2.687-.468-5.53.291-7.602 2.363l-.734.703 5.43 5.43L3 27.563V29h1.437l8.273-8.273 5.43 5.43.703-.734c2.072-2.073 2.83-4.915 2.363-7.602l6.836-5.015.958-.703L19.897 3zm.255 3.13l5.718 5.718-6.356 4.663-.575.415.191.671c.491 1.873-.044 3.825-1.214 5.462l-8.975-8.975c1.637-1.17 3.59-1.705 5.462-1.214l.67.191.416-.575 4.663-6.356z' />
  </svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
