// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg width='32' height='32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M10.79 19.793l-6.131-6.126a1.009 1.009 0 0 1 .41-1.675 11.952 11.952 0 0 1 8.284.432l4.383-4.378a9.23 9.23 0 0 1 .044-5.34.998.998 0 0 1 1.66-.413l10.265 10.262a1.009 1.009 0 0 1-.41 1.676 9.223 9.223 0 0 1-5.347.038l-4.375 4.374a11.955 11.955 0 0 1 .433 8.289.998.998 0 0 1-1.66.413l-6.138-6.134-8.503 8.497a.996.996 0 0 1-1.415-.005 1.01 1.01 0 0 1 .005-1.423l8.494-8.487zm11.173-6.376a9.201 9.201 0 0 1-3.378-3.383l-3.39 3.385a11.945 11.945 0 0 1 3.383 3.383l3.385-3.385zM24 12.166a7.217 7.217 0 0 0 2.936.458l-7.562-7.56A7.183 7.183 0 0 0 24 12.166zm-8.354 4.2a9.917 9.917 0 0 0-8.274-2.824L18.468 24.63a9.891 9.891 0 0 0-2.822-8.264z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
