// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M16.508 24.6169l-2.534-5.629 9.725-9.41-7.191 15.039zm5.876-16.55l-9.773 9.458-5.341-2.954 15.114-6.504zm5.605-3.011c.003-.038.001-.073-.001-.111-.003-.083-.018-.163-.042-.244-.011-.034-.019-.068-.033-.102-.047-.108-.107-.211-.192-.3h-.001c0-.001 0-.002-.001-.002-.004-.004-.009-.005-.013-.009-.083-.084-.179-.146-.281-.194-.034-.016-.067-.025-.103-.037-.079-.027-.159-.044-.242-.051-.037-.003-.071-.007-.108-.006-.092.003-.181.02-.27.048-.025.008-.051.01-.076.02-.007.003-.014.003-.021.006l-22 9.466c-.351.151-.584.488-.604.869-.018.381.181.74.515.925l7.482 4.138 3.571 7.931c.16.355.511.585.9.589h.012c.384 0 .736-.221.902-.569l10.52-22c.003-.008.003-.016.006-.024.013-.027.016-.054.026-.082.029-.086.05-.172.054-.261z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
