// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M26 6.2h-2.47c-4.8 0-6.59-2.63-6.66-2.74a1.1 1.1 0 0 0-1.74 0c-.07.11-1.86 2.74-6.68 2.74H6a1 1 0 0 0-1 1v5.59c0 .13 0 12.43 10.67 16.15a.94.94 0 0 0 .66 0C27 25.22 27 12.92 27 12.8V7.2a1 1 0 0 0-1-1zm-9.29 15.31a1 1 0 1 1 .29-.71 1.05 1.05 0 0 1-.29.71zM17 17a1 1 0 0 1-2 0v-6.2a1 1 0 0 1 2 0z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
