// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <path d="M9.6 26.4H4a1 1 0 0 1-1-1V11a1 1 0 0 1 1-1h5.6a1 1 0 0 1 1 1v14.4a1 1 0 0 1-1 1zm-4.6-2h3.6V12H5z"/>
  <path d="M24.8 28H16a6.08 6.08 0 0 1-3.47-1.26L9 23.77a1 1 0 1 1 1.28-1.54l3.57 3A4.22 4.22 0 0 0 16 26h8.8a.83.83 0 0 0 .78-.7L27 14.06a.44.44 0 0 0-.1-.33.45.45 0 0 0-.33-.13H19.2a1 1 0 0 1 0-2h7.37A2.4 2.4 0 0 1 29 14.3l-1.43 11.24A2.81 2.81 0 0 1 24.8 28z"/>
  <path d="M19.2 13.6a1 1 0 0 1-1-1V5.4a1 1 0 0 1 2 0v7.2a1 1 0 0 1-1 1z"/>
  <path d="M12.8 13.6H9.6a1 1 0 0 1 0-2H12c.4-1.95 1.37-6.59 1.61-7.34A3.4 3.4 0 0 1 20.2 5.4a1 1 0 1 1-2 0A1.4 1.4 0 0 0 16.8 4a1.38 1.38 0 0 0-1.29.86c-.2.61-1.14 5.09-1.73 7.94a1 1 0 0 1-.98.8z"/>
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
