
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <defs>
        <linearGradient id='a' x1='-51.395%' x2='102%' y1='-30.203%' y2='101%'>
            <stop offset='0%' stopColor='#3023AE' />
            <stop offset='100%' stopColor='#C86DD7' />
        </linearGradient>
    </defs>
    <g fill='none' fillRule='evenodd'>
        <path fill='url(#a)' d='M11.651 8.887c0-2.599 1.95-4.712 4.349-4.712 2.398 0 4.349 2.113 4.349 4.712v2.356H11.65V8.887zM23.7 11.333h-1.1V9c0-3.86-2.96-7-6.6-7-3.64 0-6.6 3.14-6.6 7v2.333H8.3c-1.82 0-3.3 1.57-3.3 3.5V26.5C5 28.43 6.48 30 8.3 30h15.4c1.82 0 3.3-1.57 3.3-3.5V14.833c0-1.93-1.48-3.5-3.3-3.5z'
        />
        <path fill='#FFF' d='M8.667 17.766v-1.388h5.644v1.388h-1.956v6.105h-1.742v-6.105H8.667zm6.095 5.337c-.57-.562-.856-1.302-.856-2.22 0-.918.285-1.653.856-2.204.57-.552 1.277-.828 2.12-.828.841 0 1.546.276 2.113.828.567.551.851 1.286.851 2.204 0 .918-.282 1.658-.846 2.22-.563.562-1.266.843-2.109.843-.842 0-1.552-.281-2.129-.843zm2.965-1.1c.23-.256.346-.626.346-1.11 0-.484-.119-.852-.356-1.104a1.123 1.123 0 0 0-.846-.38c-.326 0-.606.127-.84.38-.235.252-.352.62-.352 1.104 0 .484.12.854.362 1.11.24.257.524.385.85.385.326 0 .605-.128.836-.385zm4.71-4.088v1.11c.407-.782.95-1.174 1.63-1.174v1.858h-.428c-.401 0-.702.1-.902.298-.2.2-.3.548-.3 1.046v2.818h-1.743v-5.956h1.742z'
        />
    </g>
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
