// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License. v. 2.0. If a copy of the MPL was not distributed with this file.
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from "react";
import GenerateComponentForGraphic from "./template";

// Direct access to SVG
export const Graphic = (
  <svg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'>
    <path d='M21.07 19.546a1.076 1.076 0 1 1-1.524 1.523L16 17.523l-3.546 3.546a1.074 1.074 0 0 1-1.523 0 1.076 1.076 0 0 1 0-1.523L14.477 16l-3.546-3.546a1.076 1.076 0 1 1 1.523-1.523L16 14.477l3.546-3.546a1.076 1.076 0 1 1 1.523 1.523L17.523 16l3.546 3.546zM16 2C8.28 2 2 8.28 2 16s6.28 14 14 14 14-6.28 14-14S23.72 2 16 2z'
    />
  </svg>
);

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic);
