// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <g fillRule='evenodd' clipRule='evenodd'>
        <path d='M15.6 4.4L4.3 10.2c-.2.1-.3.4-.3.6V24c0 .2.1.5.3.6l11.3 5.8c.2.2.5.2.7 0l11.3-5.8c.2-.1.3-.4.3-.6V10.8c0-.2-.1-.5-.3-.6L16.4 4.4c-.3-.1-.5-.1-.8 0'
        fill='#bdc0c8' />
        <path d='M16.7 11c1.2 0 2.1.3 2.8.9s1.1 1.5 1.1 2.6-.3 1.9-1 2.5c-.7.6-1.6.9-2.8.9v1.5h-2.7v-3.3h1.1c.8 0 1.4-.1 1.9-.3.4-.2.7-.6.7-1.2 0-.4-.1-.7-.3-.9-.2-.2-.5-.3-.9-.3s-.7.1-.9.4c-.2.2-.3.5-.3.9h-2.7c0-.7.1-1.3.4-1.8.3-.6.8-1 1.4-1.3.5-.5 1.3-.6 2.2-.6zm.2 9.8v2.9h-3v-2.9h3z'
        fill='#fff' />
    </g>
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
