// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M16.48192 4.12378l10 5.5c.31955.17576.51808.51153.51808.87622v11c0 .3647-.19853.70046-.51808.87622l-10 5.5a1 1 0 0 1-.96384 0l-10-5.5C5.19853 22.20046 5 21.86469 5 21.5v-11c0-.3647.19853-.70046.51808-.87622l10-5.5a1 1 0 0 1 .96384 0zm2.75016 8.23614l-4.29898 5.15877-2.2257-2.2257c-.39052-.39052-1.02368-.39052-1.4142 0-.39053.39053-.39053 1.0237 0 1.41422l3 3c.4158.4158 1.09887.38481 1.47532-.06693l5-6c.35357-.42427.29624-1.05484-.12804-1.4084-.42427-.35357-1.05484-.29624-1.4084.12804z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
