// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' xmlnsXlink='http://www.w3.org/1999/xlink'
viewBox='0 0 32 32'>
    <defs>
        <path id='a' d='M6 17h6.001v-2H6v2zm17.22329 2.01232l.15175.24984c.28671.47203.13648 1.08712-.33555 1.37383s-1.08711.13649-1.37383-.33555l-1.41673-2.33243c-.29432-.48455-.12738-1.1166.36782-1.39262l2.31247-1.28894c.48241-.26888 1.09146-.0958 1.36034.38662.26889.4824.0958 1.09145-.38661 1.36034l-.08881.0495C25.63288 17.45897 27 19.06983 27 21c0 2.20914-1.79086 4-4 4-1.0244 0-1.99068-.38799-2.72544-1.0722-.40419-.37636-.42673-1.00913-.05036-1.41331s1.00914-.42673 1.41332-.05036C22.00568 22.80697 22.48642 23 23 23c1.10457 0 2-.89543 2-2 0-1.0291-.77724-1.87665-1.77671-1.98768zM25.571 7C26.91 7 28 8.101 28 9.455V15c0 .552-.447 1-1 1-.553 0-1-.448-1-1V9.455c0-.247-.196-.455-.429-.455H8.429C8.196 9 8 9.208 8 9.455V13h5.001c.553 0 1 .447 1 1v4c0 .552-.447 1-1 1H8v3.545c0 .246.196.455.429.455H16c.553 0 1 .447 1 1 0 .552-.447 1-1 1H8.429C7.09 25 6 23.898 6 22.545V19H5c-.553 0-1-.448-1-1v-4c0-.553.447-1 1-1h1V9.455C6 8.101 7.09 7 8.429 7h17.142z'
        />
    </defs>
    <use fillRule='evenodd' xlinkHref='#a' />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
