// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <g fillRule='evenodd'>
        <path d='M6 16h6.001v-2H6v2zM25.571 6H8.429C7.09 6 6 7.101 6 8.455V12H5c-.553 0-1 .448-1 1v4c0 .552.447 1 1 1h1v3.545C6 22.899 7.09 24 8.429 24H17c.553 0 1-.448 1-1s-.447-1-1-1H8.429C8.196 22 8 21.792 8 21.545V18h5.001c.553 0 1-.448 1-1v-4c0-.552-.447-1-1-1H8V8.455C8 8.208 8.196 8 8.429 8h17.142c.233 0 .429.208.429.455V17c0 .552.447 1 1 1 .553 0 1-.448 1-1V8.455C28 7.101 26.91 6 25.571 6z'
        />
        <path d='M27 22h-1.999v-2c0-.552-.447-1-1-1-.553 0-1 .448-1 1v2H21c-.553 0-1 .448-1 1s.447 1 1 1h2.001v2c0 .552.447 1 1 1 .553 0 1-.448 1-1v-2H27c.553 0 1-.448 1-1s-.447-1-1-1'
        />
    </g>
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
