// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path fillRule='evenodd' d='M24.99998 21.99313A1.02071 1.02071 0 0 1 25 22v3c0 .55228-.44772 1-1 1s-1-.44772-1-1v-3a1.0101 1.0101 0 0 1 .0074-.12224l-.99522.71334c-.44889.32175-1.0736.21868-1.39535-.2302-.32175-.4489-.21868-1.07361.2302-1.39536l2.48105-1.77832c.34613-.2481.8114-.24976 1.1593-.00415l2.51896 1.77832c.45118.31852.55872.94248.2402 1.39366-.31852.45118-.94249.55872-1.39367.2402l-.8529-.60212zM25.571 6C26.91 6 28 7.101 28 8.455V17c0 .552-.447 1-1 1-.553 0-1-.448-1-1V8.455c0-.247-.196-.455-.429-.455H8.429C8.196 8 8 8.208 8 8.455V12h5.001c.553 0 1 .448 1 1v4c0 .552-.447 1-1 1H8v3.545c0 .247.196.455.429.455H17c.553 0 1 .448 1 1s-.447 1-1 1H8.429C7.09 24 6 22.899 6 21.545V18H5c-.553 0-1-.448-1-1v-4c0-.552.447-1 1-1h1V8.455C6 7.101 7.09 6 8.429 6h17.142zM6 16h6.001v-2H6v2z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
