// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M26.43 6H7.57A2.6 2.6 0 0 0 5 8.64V12H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h1v3.36A2.6 2.6 0 0 0 7.57 26H16a1 1 0 0 0 0-2H7.57a.61.61 0 0 1-.57-.64V20h5a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1H7V8.64A.61.61 0 0 1 7.57 8h18.86a.61.61 0 0 1 .57.64V16a1 1 0 0 0 2 0V8.64A2.6 2.6 0 0 0 26.43 6zM11 18H5v-4h6z'
    />
    <path d='M8.92 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2zM23 21a1 1 0 0 0-1 1v3a1 1 0 0 0 2 0v-3a1 1 0 0 0-1-1zM23.56 18.17a.76.76 0 0 0-.18-.09L23.2 18a1 1 0 0 0-.58.06 1.15 1.15 0 0 0-.33.21A1.05 1.05 0 0 0 22 19a1 1 0 0 0 .08.38 1 1 0 0 0 .21.33 1.15 1.15 0 0 0 .33.21A1 1 0 0 0 23 20h.2l.18-.06a.76.76 0 0 0 .18-.09 1.58 1.58 0 0 0 .15-.12 1 1 0 0 0 .21-.33A1 1 0 0 0 24 19a1.05 1.05 0 0 0-.29-.71z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
