// THIS FILE IS AUTOGENERATED, DO NOT MODIFY MANUALLY
/* tslint:disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License. v. 2.0. If a copy of the MPL was not distributed with this file.
* You can obtain one at http://mozilla.org/MPL/2.0/. */

import * as React from 'react'
import GenerateComponentForGraphic from './template'

// Direct access to SVG
export const Graphic = (
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'>
    <path d='M26.43 6H7.57A2.6 2.6 0 0 0 5 8.64V12H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h1v3.36A2.6 2.6 0 0 0 7.57 26H16a1 1 0 0 0 0-2H7.57a.61.61 0 0 1-.57-.64V20h5a1 1 0 0 0 1-1v-6a1 1 0 0 0-1-1H7V8.64A.61.61 0 0 1 7.57 8h18.86a.61.61 0 0 1 .57.64V13a1 1 0 0 0 2 0V8.64A2.6 2.6 0 0 0 26.43 6zM11 18H5v-4h6z'
    />
    <path d='M28 18.17h-1v-.67a3.29 3.29 0 0 0-3-3.5 3.29 3.29 0 0 0-3 3.5v.67h-1a1 1 0 0 0-1 1V25a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-5.83a1 1 0 0 0-1-1zm-5-.67c0-.8.47-1.5 1-1.5s1 .7 1 1.5v.67h-2zm4 6.5h-6v-3.83h6zM8.92 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2z'
    />
</svg>
)

// Styled Component for SVG
export default GenerateComponentForGraphic(Graphic)
